"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { explainFirestoreError, registerProfile } from "../../lib/firestore";
import { authenticateForSignup, explainAuthError, signupDestination } from "../../lib/auth/signup";

export default function CustomerSignup() {
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  async function signup(event) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); try { const { user, profile } = await authenticateForSignup(form.get("email"), form.get("password"), "client"); if (!profile) await registerProfile(user, { displayName: form.get("name"), email: form.get("email"), phone: form.get("phone"), country: form.get("country"), city: form.get("city"), role: "client" }); router.replace(signupDestination("client")); } catch (error) { setError(error.code === "permission-denied" || error.code === "failed-precondition" || error.code === "unavailable" ? explainFirestoreError(error) : explainAuthError(error)); } finally { setLoading(false); } }
  return <main className="auth-page"><Link className="auth-back" href="/"><ArrowLeft size={17} />Retour à Miamgo</Link><section className="auth-card"><div className="auth-card-brand"><img src="/miamgo-logo.png" alt="Miamgo" /></div><p className="eyebrow">COMPTE CLIENT</p><h1>Vos bons repas commencent ici.</h1><p className="auth-intro">Créez votre compte pour commander, enregistrer vos restaurants et suivre vos livraisons.</p><form onSubmit={signup}><label><UserRound size={16} />Nom complet<input name="name" required placeholder="Votre nom" /></label><label>Numéro WhatsApp<input name="phone" required placeholder="+229 00 00 00 00" /></label><label>Pays<select name="country" defaultValue="BJ"><option value="BJ">Bénin (BJ)</option><option value="CI">Côte d&apos;Ivoire (CI)</option><option value="TG">Togo (TG)</option><option value="SN">Sénégal (SN)</option><option value="CV">Cap-Vert (CV)</option><option value="GM">Gambie (GM)</option><option value="GH">Ghana (GH)</option><option value="GN">Guinée (GN)</option><option value="GW">Guinée-Bissau (GW)</option><option value="LR">Libéria (LR)</option><option value="NG">Nigeria (NG)</option><option value="SL">Sierra Leone (SL)</option></select></label><label>Ville<input name="city" required defaultValue="Cotonou" placeholder="Votre ville" /></label><label>Adresse e-mail<input name="email" type="email" required placeholder="vous@exemple.com" /></label><label>Mot de passe<input name="password" type="password" required minLength="6" placeholder="6 caractères minimum" /></label>{error && <p className="auth-error">{error}</p>}<button disabled={loading}>{loading ? "Création..." : "Créer mon compte client"}</button></form><p className="auth-foot"><CheckCircle2 size={15} />Déjà inscrit? <Link href="/connexion">Se connecter</Link></p></section></main>;
}
