"use client";

import { useState } from "react";
import Link from "next/link";
import { Bell, Bookmark, Clock3, Heart, MapPin, PackageCheck, Settings, ShoppingBag } from "lucide-react";
import PlatformShell from "../../components/PlatformShell";

export default function CustomerProfile() {
  const [tab, setTab] = useState("overview");
  return <PlatformShell><main className="content-wrap profile-page"><div className="profile-heading"><div className="profile-avatar">MA</div><div><p className="eyebrow">ESPACE CLIENT</p><h1>Marie Adjoua</h1><p>marie@miamgo.app · Cotonou</p></div><button onClick={() => setTab("settings")}><Settings size={17} />Paramètres</button></div><nav className="profile-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Vue d&apos;ensemble</button><button className={tab === "favorites" ? "active" : ""} onClick={() => setTab("favorites")}>Favoris</button><button className={tab === "addresses" ? "active" : ""} onClick={() => setTab("addresses")}>Adresses</button><button className={tab === "notifications" ? "active" : ""} onClick={() => setTab("notifications")}>Notifications</button></nav>{tab === "overview" && <div className="profile-grid"><section><h2>Commande en cours</h2><article className="profile-order"><PackageCheck size={23} /><div><strong>Chez Aïcha · #MG-0842</strong><p>Riz gras au poulet fumé · En préparation</p></div><Link href="/commandes">Suivre</Link></article><h2>Vos dernières commandes</h2><Link className="history-link" href="/commandes"><Clock3 size={18} /><span><strong>Retrouvez tous vos repas</strong><small>Historique, factures et codes QR</small></span>→</Link></section><aside><h2>Vos raccourcis</h2><button onClick={() => setTab("favorites")}><Heart size={18} />Restaurants favoris</button><Link href="/panier"><ShoppingBag size={18} />Mon panier</Link><button onClick={() => setTab("addresses")}><MapPin size={18} />Mes adresses</button></aside></div>}{tab === "favorites" && <section className="profile-panel"><h2>Restaurants sauvegardés</h2><article><span>CA</span><div><strong>Chez Aïcha</strong><p>Cuisine béninoise · Cadjèhoun</p></div><Link href="/restaurant/chez-aicha">Voir le menu</Link></article></section>}{tab === "addresses" && <section className="profile-panel"><h2>Mes adresses</h2><article><MapPin size={20} /><div><strong>Maison</strong><p>Cadjèhoun, près du carrefour</p></div><button onClick={() => setTab("settings")}>Modifier</button></article><button className="add-address" onClick={() => alert("L'ajout d'adresse sera enregistré dans votre profil Firestore.")}>+ Ajouter une adresse</button></section>}{tab === "notifications" && <section className="profile-panel"><h2>Notifications</h2><article><Bell size={20} /><div><strong>Votre commande est en préparation</strong><p>Chez Aïcha prépare votre repas.</p></div></article><article><Bookmark size={20} /><div><strong>Nouvelle promotion</strong><p>Mami Grill propose le poisson braisé ce soir.</p></div></article></section>}{tab === "settings" && <section className="profile-panel"><h2>Préférences du compte</h2><p>Les modifications de profil seront synchronisées avec Firestore.</p><button className="add-address" onClick={() => setTab("overview")}>Enregistrer les préférences</button></section>}</main></PlatformShell>;
}
