"use client";

import { useState } from "react";
import Link from "next/link";
import { CheckCircle2, ChevronRight, Clock3, MapPin, PackageCheck, QrCode, Store, Truck, X } from "lucide-react";
import PlatformShell from "../../components/PlatformShell";

export default function OrdersPage() {
  const [tab, setTab] = useState("En cours");
  const [pickup, setPickup] = useState(false);
  const [showQr, setShowQr] = useState(false);
  const tabs = ["En cours", "Terminées", "Annulées"];
  return <PlatformShell active="Commandes"><main className="content-wrap orders-page"><p className="eyebrow">VOS REPAS</p><h1>Mes commandes</h1><div className="order-tabs">{tabs.map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}{item === "En cours" && <span>1</span>}</button>)}</div>{tab === "En cours" ? <><section className="active-order"><div className="active-order-header"><div><span className="live-dot" />{pickup ? "Prête au retrait" : "En préparation"}</div><p>Commande <b>#MG-0842</b></p></div><div className="order-restaurant"><span>CA</span><div><h2>Chez Aïcha</h2><p>Riz gras au poulet fumé · Jus de bissap</p></div><Link href="/restaurant/chez-aicha">Voir le resto <ChevronRight size={16} /></Link></div><div className="order-progress"><div className="progress-step done"><span><CheckCircle2 size={17} /></span><p>Commande<br /><b>confirmée</b></p></div><i className="filled" /><div className="progress-step current"><span><PackageCheck size={17} /></span><p>En cours de<br /><b>préparation</b></p></div><i /><div className="progress-step"><span><Truck size={17} /></span><p>En cours de<br /><b>livraison</b></p></div><i /><div className="progress-step"><span><MapPin size={17} /></span><p>Commande<br /><b>livrée</b></p></div></div><div className="ready-time"><Clock3 size={18} /><p><strong>{pickup ? "Votre repas est prêt pour le retrait." : "Votre repas sera prêt dans environ 18 min."}</strong><span>Le restaurant vous notifiera dès qu&apos;il sera prêt.</span></p></div><div className="order-actions"><button onClick={() => setPickup(!pickup)}><Store size={17} />{pickup ? "Retrait sélectionné" : "Passer au retrait"}</button><button className="secondary" onClick={() => setShowQr(true)}><QrCode size={17} />Afficher mon code QR</button></div></section>{showQr && <div className="modal-backdrop"><section className="qr-modal"><button onClick={() => setShowQr(false)}><X size={19} /></button><p className="eyebrow">RETRAIT CHEZ AÏCHA</p><h2>Commande #MG-0842</h2><div className="fake-qr">MG<br />0842</div><p>Présentez ce code à l&apos;employé du restaurant pour valider le retrait.</p></section></div>}</> : <section className="empty-state"><PackageCheck size={34} /><h2>Aucune commande {tab.toLowerCase()}</h2><p>Vos commandes apparaîtront ici.</p></section>}<section className="past-orders"><div className="section-heading"><div><p className="eyebrow">VOS DERNIERS REPAS</p><h2>Historique</h2></div><button onClick={() => setTab("Terminées")}>Tout voir</button></div><article><div className="past-food">🍝</div><div><h3>Le Comptoir de Koffi</h3><p>Spaghetti bolognaise · 22 juillet</p></div><strong>1 800 FCFA</strong><span>Terminée</span></article></section></main></PlatformShell>;
}
