import { useEffect, useState } from "react";
import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { StatusBar } from "expo-status-bar";
import { signInWithEmailAndPassword, onAuthStateChanged, signOut } from "firebase/auth";
import { addDoc, collection, doc, getDoc, serverTimestamp, updateDoc } from "firebase/firestore";
import { auth, db } from "./src/firebase";
import { Home, LogIn, MapPin, Package, Search, Settings, ShoppingBag, Store, UserRound, X } from "lucide-react-native";

const posts = [
  { restaurant: "Chez Aïcha", dish: "Riz gras au poulet fumé", price: 2500, image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=85" },
  { restaurant: "Mami Grill", dish: "Poisson braisé & alloco", price: 3000, image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85" },
];

export default function App() {
  const [user, setUser] = useState(null); const [profile, setProfile] = useState(null); const [screen, setScreen] = useState("Accueil"); const [authMode, setAuthMode] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [query, setQuery] = useState(""); const [cart, setCart] = useState([]); const [busy, setBusy] = useState(false);
  useEffect(() => onAuthStateChanged(auth, async (session) => { setUser(session); if (session) { const snapshot = await getDoc(doc(db, "users", session.uid)).catch(() => null); setProfile(snapshot?.exists() ? snapshot.data() : null); } else setProfile(null); }), []);
  const role = profile?.role || "client";
  async function login() { setBusy(true); try { await signInWithEmailAndPassword(auth, email.trim(), password); setAuthMode(false); } catch (error) { Alert.alert("Connexion impossible", error.code || "Vérifiez vos identifiants."); } finally { setBusy(false); } }
  async function createOrder() { if (!user) { setAuthMode(true); return; } if (!cart.length) return; setBusy(true); try { await addDoc(collection(db, "orders"), { customerId: user.uid, restaurantId: "chez-aicha", restaurantName: "Chez Aïcha", items: cart, amount: cart.reduce((sum, item) => sum + item.price, 0), status: "pending", paymentStatus: "pending", fulfillmentType: "pickup", createdAt: serverTimestamp() }); setCart([]); setScreen("Commandes"); Alert.alert("Commande créée", "Le paiement FedaPay sera ajouté avant la mise en production."); } catch { Alert.alert("Erreur", "Firestore a refusé la commande. Vérifiez vos règles."); } finally { setBusy(false); } }
  const visible = posts.filter((post) => `${post.restaurant} ${post.dish}`.toLowerCase().includes(query.toLowerCase()));
  if (authMode) return <AuthScreen email={email} password={password} setEmail={setEmail} setPassword={setPassword} login={login} busy={busy} close={() => setAuthMode(false)} />;
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" /><View style={styles.container}><Header user={user} role={role} signOut={() => signOut(auth)} /><View style={styles.content}>{role === "restaurant_owner" && screen === "Tableau" ? <RestaurantDashboard onScan={() => setScreen("Scanner")} /> : role === "driver" && screen === "Courses" ? <DriverDashboard user={user} profile={profile} /> : screen === "Scanner" ? <ScannerScreen onBack={() => setScreen(role === "driver" ? "Courses" : "Tableau")} /> : screen === "Panier" ? <CartScreen cart={cart} remove={(index) => setCart((items) => items.filter((_, itemIndex) => itemIndex !== index))} order={createOrder} busy={busy} /> : <FeedScreen query={query} setQuery={setQuery} posts={visible} add={(post) => setCart((items) => [...items, post])} />}</View><BottomNav role={role} screen={screen} setScreen={setScreen} cart={cart} /></View></SafeAreaView>;
}

function Header({ user, role, signOut }) { return <View style={styles.header}><Image source={require("./assets/icon.png")} style={styles.logoImage} resizeMode="contain" /><View style={styles.location}><MapPin size={14} color="#ef6a38" /><Text>Cotonou, BJ</Text></View>{user ? <Pressable onPress={signOut}><LogIn size={20} color="#275d49" /></Pressable> : <UserRound size={20} color="#275d49" />}</View>; }
function FeedScreen({ query, setQuery, posts, add }) { return <><View style={styles.title}><Text style={styles.kicker}>AUTOUR DE VOUS</Text><Text style={styles.heading}>Qu&apos;est-ce qui vous fait envie?</Text></View><View style={styles.search}><Search size={18} color="#718078" /><TextInput style={styles.searchInput} value={query} onChangeText={setQuery} placeholder="Rechercher un plat..." /></View><ScrollView contentContainerStyle={styles.feed}>{posts.map((post) => <View style={styles.card} key={post.dish}><Image source={{ uri: post.image }} style={styles.food} /><View style={styles.cardBody}><Text style={styles.restaurant}>{post.restaurant}</Text><Text style={styles.dish}>{post.dish}</Text><View style={styles.meta}><Text>Disponible maintenant</Text><Text style={styles.price}>{post.price.toLocaleString("fr-FR")} FCFA</Text></View><Pressable style={styles.addButton} onPress={() => add(post)}><ShoppingBag size={15} color="#fff" />Ajouter au panier</Pressable></View></View>)}</ScrollView></>; }
function CartScreen({ cart, remove, order, busy }) { return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>COMMANDE</Text><Text style={styles.heading}>Mon panier</Text>{cart.length ? cart.map((item, index) => <View style={styles.cartRow} key={`${item.dish}-${index}`}><View><Text style={styles.dish}>{item.dish}</Text><Text>{item.price.toLocaleString("fr-FR")} FCFA</Text></View><Pressable onPress={() => remove(index)}><X size={18} color="#d05243" /></Pressable></View>) : <Text style={styles.muted}>Votre panier est vide.</Text>}{cart.length > 0 && <Pressable style={styles.primary} onPress={order} disabled={busy}><Text style={styles.primaryText}>{busy ? "Création..." : "Créer la commande"}</Text></Pressable>}</ScrollView>; }
function AuthScreen({ email, password, setEmail, setPassword, login, busy, close }) { return <View style={styles.auth}><Text style={styles.logo}><Text style={styles.orange}>miam</Text>go.</Text><Text style={styles.heading}>Connexion</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="E-mail ou téléphone" autoCapitalize="none" /><TextInput style={styles.input} value={password} onChangeText={setPassword} placeholder="Mot de passe" secureTextEntry /><Pressable style={styles.primary} onPress={login}><Text style={styles.primaryText}>{busy ? "Connexion..." : "Se connecter"}</Text></Pressable><Pressable onPress={close}><Text style={styles.link}>Continuer sans compte</Text></Pressable></View>; }
function RestaurantDashboard({ onScan }) { return <View style={styles.page}><Text style={styles.kicker}>ESPACE RESTAURANT</Text><Text style={styles.heading}>Commandes</Text><View style={styles.metric}><Package size={22} color="#ef6a38" /><Text style={styles.dish}>3 nouvelles commandes</Text></View><Pressable style={styles.primary} onPress={onScan}><Text style={styles.primaryText}>Scanner un retrait QR</Text></Pressable><Text style={styles.muted}>Préparation · Prêtes · Livraison · Programmées</Text></View>; }
function DriverDashboard({ user, profile }) { const [available,setAvailable]=useState(profile?.availabilityStatus === "available"); const verified=profile?.verificationStatus === "approved"; const active=profile?.subscriptionStatus === "active"; async function toggle(){if(!user||!verified||!active)return;const next=!available;setAvailable(next);await updateDoc(doc(db,"users",user.uid),{availabilityStatus:next?"available":"unavailable"}).catch(()=>setAvailable(!next));} return <ScrollView contentContainerStyle={styles.driverHome}><Text style={styles.kicker}>ACCUEIL LIVREUR</Text><Text style={styles.heading}>Votre disponibilité</Text><View style={[styles.availabilityCard,available&&styles.available]}><View><Text style={styles.dish}>{available?"Vous êtes disponible":"Vous êtes indisponible"}</Text><Text style={styles.muted}>{!verified?"Compte en attente de validation":!active?"Abonnement requis":"Les restaurants peuvent vous proposer des courses"}</Text></View><Pressable style={styles.toggle} onPress={toggle} disabled={!verified||!active}><Text style={styles.primaryText}>{available?"Indisponible":"Disponible"}</Text></Pressable></View>{!verified&&<View style={styles.notice}><Text style={styles.dish}>Validation en attente</Text><Text style={styles.muted}>Votre pièce d’identité doit être vérifiée avant l’accès aux courses.</Text></View>}{verified&&!active&&<View style={styles.notice}><Text style={styles.dish}>Compte validé, abonnement requis</Text><Text style={styles.muted}>Activez votre abonnement depuis votre profil.</Text></View>}<View style={styles.emptyRequest}><MapPin size={28} color="#ef6a38"/><Text style={styles.dish}>Aucune demande pour le moment</Text><Text style={styles.muted}>Restez disponible, les demandes apparaîtront ici.</Text></View><View style={styles.daySummary}><Text style={styles.kicker}>AUJOURD&apos;HUI</Text><Text style={styles.dish}>Courses effectuées: --</Text><Text style={styles.dish}>Gain du jour: -- FCFA</Text></View></ScrollView>; }
function ScannerScreen({ onBack }) { const [permission, requestPermission] = useCameraPermissions(); return <View style={styles.scanner}>{!permission?.granted ? <><Text style={styles.heading}>Scanner un QR</Text><Text style={styles.muted}>Autorisez la caméra pour valider la commande.</Text><Pressable style={styles.primary} onPress={requestPermission}><Text style={styles.primaryText}>Autoriser la caméra</Text></Pressable></> : <CameraView style={styles.camera} barcodeScannerSettings={{ barcodeTypes: ["qr"] }} onBarcodeScanned={({ data }) => Alert.alert("QR détecté", data)}><View style={styles.scanFrame} /></CameraView>}<Pressable onPress={onBack}><Text style={styles.link}>Retour</Text></Pressable></View>; }
function BottomNav({ role, screen, setScreen, cart }) { const items = role === "restaurant_owner" ? [["Fil","Accueil",Home],["Commandes","Tableau",Package],["Plus","Plus",Settings]] : role === "driver" ? [["Accueil","Courses",Home],["Historique","Historique",Package],["Profil","Profil",UserRound]] : [["Accueil","Accueil",Home],["Explorer","Explorer",Search],["Panier","Panier",ShoppingBag],["Commandes","Commandes",Package],["Profil","Profil",UserRound]]; return <View style={styles.nav}>{items.map(([label,target,Icon]) => <Pressable style={styles.navItem} onPress={() => setScreen(target)} key={label}><Icon size={21} color={screen === target ? "#ef6a38" : "#718078"} /><Text style={[styles.navLabel, screen === target && styles.active]}>{label}{target === "Panier" && cart.length ? ` (${cart.length})` : ""}</Text></Pressable>)}</View>; }

const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:"#f2eee5"},container:{flex:1,paddingHorizontal:16},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},logoImage:{width:112,height:48},logo:{color:"#275d49",fontSize:27,fontWeight:"900",letterSpacing:-2},orange:{color:"#ef6a38"},location:{flexDirection:"row",alignItems:"center",gap:4},content:{flex:1},title:{paddingTop:18,paddingBottom:14},kicker:{color:"#ef6a38",fontSize:10,fontWeight:"800",letterSpacing:1},heading:{color:"#1f2a24",fontSize:25,fontWeight:"800",marginBottom:14},search:{height:46,flexDirection:"row",alignItems:"center",gap:9,paddingHorizontal:13,backgroundColor:"#fffaf1",borderRadius:12},searchInput:{flex:1,color:"#1f2a24"},feed:{paddingVertical:16,paddingBottom:90,gap:15},card:{overflow:"hidden",backgroundColor:"#fffaf1",borderRadius:16},food:{width:"100%",height:205},cardBody:{padding:14},restaurant:{color:"#ef6a38",fontSize:11,fontWeight:"800"},dish:{marginTop:4,color:"#1f2a24",fontSize:17,fontWeight:"800"},meta:{marginTop:11,flexDirection:"row",justifyContent:"space-between"},price:{color:"#275d49",fontWeight:"800"},addButton:{marginTop:12,padding:10,flexDirection:"row",justifyContent:"center",alignItems:"center",gap:5,backgroundColor:"#275d49",borderRadius:8},primary:{padding:13,marginTop:18,alignItems:"center",backgroundColor:"#275d49",borderRadius:9},primaryText:{color:"#fff",fontWeight:"800"},nav:{position:"absolute",right:0,bottom:0,left:0,height:68,paddingHorizontal:5,flexDirection:"row",justifyContent:"space-around",alignItems:"center",backgroundColor:"#fffaf1",borderTopWidth:1,borderTopColor:"#ded7ca"},navItem:{alignItems:"center",gap:4},navLabel:{color:"#718078",fontSize:9},active:{color:"#ef6a38",fontWeight:"800"},page:{flex:1,paddingTop:18},muted:{color:"#718078",fontSize:12,marginTop:8},cartRow:{padding:14,marginBottom:8,flexDirection:"row",justifyContent:"space-between",backgroundColor:"#fffaf1",borderRadius:10},auth:{flex:1,justifyContent:"center",gap:14,padding:24,backgroundColor:"#f2eee5"},input:{height:46,paddingHorizontal:12,backgroundColor:"#fffaf1",borderRadius:8},link:{marginTop:14,textAlign:"center",color:"#ef6a38",fontWeight:"800"},metric:{padding:16,flexDirection:"row",gap:10,alignItems:"center",backgroundColor:"#fffaf1",borderRadius:11},scanner:{flex:1,paddingTop:18},camera:{height:380,overflow:"hidden",alignItems:"center",justifyContent:"center",borderRadius:14},scanFrame:{width:220,height:220,borderWidth:3,borderColor:"#ffcb70",borderRadius:18} });

Object.assign(styles,{driverHome:{paddingTop:18,paddingBottom:90,gap:14},availabilityCard:{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#fff1d8',borderRadius:12},available:{backgroundColor:'#e8f3e9'},toggle:{padding:10,backgroundColor:'#275d49',borderRadius:8},notice:{padding:14,backgroundColor:'#fff1d8',borderRadius:10},emptyRequest:{padding:30,alignItems:'center',gap:7,backgroundColor:'#fffaf1',borderRadius:12},daySummary:{padding:15,backgroundColor:'#fffaf1',borderRadius:12}});
