"use client";

import Link from "next/link";
import { ArrowUpRight, BarChart3, BellRing, ClipboardList, Crown, ImagePlus, PackagePlus, Store, Wallet } from "lucide-react";
import PlatformShell from "../../components/PlatformShell";

const actions = [["Ajouter un plat", "Construisez votre carte et rendez vos plats visibles.", "/espace-resto/menu", PackagePlus], ["Publier dans le fil", "Partagez une nouveauté avec vos futurs clients.", "/espace-resto/publier", ImagePlus], ["Configurer les paiements", "Recevez vos reversements avec vos coordonnées bénéficiaire.", "/espace-resto/paiement", Wallet]];

export default function RestaurantDashboard() {
  return <PlatformShell><main className="dashboard-page restaurant-dashboard-page"><section className="dashboard-content"><div className="dashboard-welcome-card"><div><p className="eyebrow">ESPACE RESTAURANT</p><h1>Votre boutique commence ici.</h1><p>Préparez votre catalogue, configurez vos paiements et recevez vos premières commandes.</p></div><div className="dashboard-welcome-orb"><Store size={42}/></div></div><div className="dashboard-heading"><div><p className="eyebrow">VUE D&apos;ENSEMBLE</p><h2>Votre activité</h2></div><Link href="/espace-resto/menu" className="dashboard-primary-action"><PackagePlus size={17}/>Ajouter un plat</Link></div><div className="metric-grid visual-metric-grid"><article><Wallet size={20}/><p>Ventes</p><strong>--</strong><small>Après vos premières commandes</small></article><article><ClipboardList size={20}/><p>Commandes</p><strong>--</strong><small>Aucune donnée reçue</small></article><article><Store size={20}/><p>Plats actifs</p><strong>--</strong><small>Votre catalogue est vide</small></article></div><section className="dashboard-setup-card"><div className="setup-icon"><Crown size={22}/></div><div><p className="eyebrow">PREMIÈRE ÉTAPE</p><h2>Donnez vie à votre boutique</h2><p>Ajoutez vos plats, vos coordonnées de paiement et votre première publication pour être prêt à recevoir des commandes.</p></div><Link href="/espace-resto/plus"><ArrowUpRight size={17}/></Link></section><section className="dashboard-orders visual-empty-panel"><div className="section-heading"><div><p className="eyebrow">COMMANDES</p><h2>Votre activité récente</h2></div><Link href="/espace-resto/commandes">Voir tout</Link></div><div className="dashboard-empty-illustration"><div><ClipboardList size={28}/></div><h3>Votre espace est prêt</h3><p>Les commandes payées apparaîtront ici en temps réel.</p></div></section><section className="dashboard-action-grid"><div className="section-heading"><div><p className="eyebrow">POUR COMMENCER</p><h2>Les raccourcis utiles</h2></div><BarChart3 size={20}/></div><div>{actions.map(([title, description, href, Icon]) => <Link href={href} key={title}><span><Icon size={19}/></span><strong>{title}</strong><small>{description}</small><ArrowUpRight size={15}/></Link>)}</div></section><Link className="dashboard-publish-banner" href="/espace-resto/publier"><BellRing size={20}/><span><strong>Votre prochaine publication</strong><small>Montrez votre univers aux clients du fil Miamgo.</small></span><ArrowUpRight size={17}/></Link></section></main></PlatformShell>;
}
