"use client";

import { useState } from "react";
import Link from "next/link";
import { Check, ChevronLeft, Mail, Store, Truck, UserRound } from "lucide-react";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
import { useRouter } from "next/navigation";
import PlatformShell from "../../components/PlatformShell";
import { auth } from "../../lib/firebase";
import { createRestaurant, registerProfile } from "../../lib/firestore";

const plans = [["basic", "Basique", "2 500 FCFA", ["Boutique en ligne", "Menu et plats du jour", "Commandes et retrait QR"]], ["pro", "Pro", "5 000 FCFA", ["Tout le plan Basique", "Promotions et statistiques", "Équipe et livreurs internes"]], ["premium", "Premium IA", "12 000 FCFA", ["Tout le plan Pro", "Agent IA restaurant", "Recommandations clients"]]];

export default function RestaurantOnboarding() {
  const [plan, setPlan] = useState("pro"); const [delivery, setDelivery] = useState("internal"); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  async function submitRestaurant(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setStatus(""); let credential; try { credential = await createUserWithEmailAndPassword(auth, form.get("email"), form.get("password")); } catch (authError) { if (authError.code !== "auth/email-already-in-use") { setStatus("Impossible de créer le compte Firebase."); setLoading(false); return; } try { credential = await signInWithEmailAndPassword(auth, form.get("email"), form.get("password")); } catch { setStatus("Cet e-mail possède déjà un compte. Connectez-vous ou utilisez son mot de passe pour finaliser l'inscription."); setLoading(false); return; } } try { await registerProfile(credential.user, { displayName: form.get("ownerName"), phone: form.get("phone"), country: form.get("country"), city: form.get("city"), role: "restaurant_owner" }); const name = form.get("name").trim(); const slug = name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); await createRestaurant(credential.user.uid, { slug, name, category: form.get("category"), phone: form.get("phone"), address: form.get("address"), country: form.get("country"), city: form.get("city"), plan, deliveryMode: delivery }); router.push("/espace-resto"); } catch { setStatus("Le compte Firebase existe, mais Firestore bloque le profil ou la boutique. Publiez les règles Firestore, puis réessayez avec les mêmes identifiants."); } finally { setLoading(false); } }
  return <PlatformShell><main className="onboarding-page"><Link className="back-link" href="/"><ChevronLeft size={17} />Retour à Miamgo</Link><div className="onboarding-title"><p className="eyebrow">COMPTE RESTAURANT</p><h1>Créez votre espace professionnel.</h1><p>Ce compte est distinct d&apos;un compte client. Il donne accès à votre boutique, vos menus, commandes, livreurs et statistiques.</p></div><form className="onboarding-form" onSubmit={submitRestaurant}><section><h2>Votre compte restaurant</h2><label><UserRound size={14} />Nom du responsable<input name="ownerName" required placeholder="Votre nom" /></label><label><Mail size={14} />Adresse e-mail professionnelle<input name="email" type="email" required placeholder="restaurant@exemple.com" /></label><label>Mot de passe<input name="password" type="password" required minLength="6" placeholder="6 caractères minimum" /></label></section><section><h2>Votre établissement</h2><label>Nom du restaurant<input name="name" required placeholder="Ex. Chez Aïcha" /></label><label>Type de cuisine<select name="category" defaultValue=""><option value="" disabled>Sélectionnez une catégorie</option><option>Cuisine béninoise</option><option>Grillades</option><option>Pâtes et pizzas</option><option>Pâtisserie</option></select></label><label>Numéro WhatsApp<input name="phone" required type="tel" placeholder="+229 00 00 00 00" /></label><label>Adresse<input name="address" required placeholder="Quartier, rue, ville" /></label></section><section><h2>Votre formule</h2><div className="plan-options">{plans.map(([id, title, price, features]) => <button type="button" className={plan === id ? "selected" : ""} onClick={() => setPlan(id)} key={id}><div><strong>{title}</strong><b>{price}<small>/mois</small></b></div><ul>{features.map((feature) => <li key={feature}><Check size={14} />{feature}</li>)}</ul></button>)}</div></section><section><h2>Livraison</h2><div className="delivery-options onboarding-delivery"><button type="button" className={delivery === "internal" ? "selected" : ""} onClick={() => setDelivery("internal")}><Truck size={22} /><div><strong>J&apos;ai mes propres livreurs</strong><span>Vous les ajouterez après création de la boutique.</span></div>{delivery === "internal" && <Check size={17} />}</button><button type="button" className={delivery === "partner" ? "selected" : ""} onClick={() => setDelivery("partner")}><Store size={22} /><div><strong>Utiliser le réseau Miamgo</strong><span>Accédez aux livreurs et agences partenaires.</span></div>{delivery === "partner" && <Check size={17} />}</button></div></section><button className="create-restaurant" type="submit" disabled={loading}>{loading ? "Création du compte..." : "Créer mon compte restaurant"}</button>{status && <p className="onboarding-status">{status}</p>}<p className="onboarding-login">Vous avez déjà un compte restaurant? <Link href="/connexion">Se connecter</Link></p></form></main></PlatformShell>;
}
