"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, ChefHat, Clock3, ScanLine, Truck } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import PlatformShell from "../../../../components/PlatformShell";
import { auth } from "../../../../lib/firebase";
import { getDriverGroupsForRestaurant, getOwnedRestaurant } from "../../../../lib/firestore";

export default function CustomerRestaurantOrders() {
  const [customer, setCustomer] = useState(null); const [orders, setOrders] = useState([]); const [drivers, setDrivers] = useState({ affiliated: [], platform: [] }); const [loading, setLoading] = useState(null); const [message, setMessage] = useState(""); const customerId = typeof window !== "undefined" ? window.location.pathname.split("/").pop() : "";
  async function load(user) { const token = await user.getIdToken(); const response = await fetch(`/api/orders/restaurant-clients?customerId=${customerId}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setCustomer(payload.customer); setOrders(payload.orders || []); const owned = await getOwnedRestaurant(user.uid).catch(() => null); if (owned) setDrivers(await getDriverGroupsForRestaurant(owned.id).catch(() => ({ affiliated: [], platform: [] })) ); }
  useEffect(() => { let timer; const stop = onAuthStateChanged(auth, async (user) => { if (user) { await load(user).catch((error) => setMessage(error.message)); timer = window.setInterval(() => load(user).catch(() => {}), 5000); } }); return () => { stop(); window.clearInterval(timer); }; }, [customerId]);
  async function action(orderId, actionName, driverId) { const token = await auth.currentUser.getIdToken(); setLoading(orderId); try { const response = await fetch("/api/orders/restaurant-action", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ orderId, action: actionName, driverId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); await load(auth.currentUser); } catch (error) { setMessage(error.message); } finally { setLoading(null); } }
  const expired = (order) => { const value = order.driverOfferExpiresAt?.toMillis?.() || (order.driverOfferExpiresAt?.seconds ? order.driverOfferExpiresAt.seconds * 1000 : 0); return value > 0 && value < Date.now(); };
  return <PlatformShell hideMobileNav><main className="content-wrap restaurant-customer-orders"><Link className="back-link" href="/espace-resto/commandes"><ArrowLeft size={17}/>Retour aux clients</Link>{customer && <header className="restaurant-customer-header"><span className="restaurant-client-avatar">{customer.photoURL ? <img src={customer.photoURL} alt="" /> : (customer.displayName || "C").slice(0, 2).toUpperCase()}</span><div><p className="eyebrow">FICHE CLIENT</p><h1>{customer.displayName || "Client Miamgo"}</h1><p>{customer.email || customer.phone || "Historique de commandes"}</p></div></header>}{message && <p className="settings-notice">{message}</p>}{orders.length ? <section className="restaurant-customer-order-list">{orders.map((order) => <article className="restaurant-order-card" key={order.id}><header><div><strong>{order.serialNumber || order.id}</strong><small>{order.deliveryMode === "pickup" ? "Retrait sur place" : "Livraison"} · {order.paymentStatus === "paid" ? "Payée" : "Paiement en attente"}</small></div><span className="order-status-tag">{order.status || "pending"}</span></header><div className="restaurant-order-items">{(order.items || []).map((item, index) => <span key={`${item.id}-${index}`}>{item.quantity || 1} × {item.name || item.dish}</span>)}</div><footer>{order.status === "paid" && <button type="button" onClick={() => action(order.id, "preparing")} disabled={loading === order.id}><ChefHat size={15}/>Préparer</button>}{["preparing", "preparation"].includes(order.status) && <button type="button" onClick={() => action(order.id, "ready")} disabled={loading === order.id}><Check size={15}/>Marquer prête</button>}{order.status === "ready" && order.deliveryMode === "pickup" && <Link className="restaurant-order-scan-button" href={`/espace-resto/scanner?order=${order.id}`}><ScanLine size={15}/>Scanner le QR</Link>}{(order.status === "ready" || (order.status === "driver_requested" && expired(order))) && order.deliveryMode === "delivery" && <select defaultValue="" onChange={(event) => event.target.value && action(order.id, "assign", event.target.value)}><option value="">Choisir un livreur</option>{[...drivers.affiliated, ...drivers.platform].map((driver) => <option value={driver.id} key={driver.id}>{driver.displayName || "Livreur"}</option>)}</select>}{order.status === "driver_requested" && !expired(order) && <span className="order-ready-note"><Clock3 size={15}/>Confirmation livreur en cours</span>}{order.status === "assigned" && <span className="order-ready-note"><Truck size={15}/>Livreur confirmé</span>}</footer></article>)}</section> : <section className="empty-state"><Clock3 size={30}/><h2>Aucune commande</h2><p>Ce client n&apos;a pas encore commandé dans votre établissement.</p></section>}</main></PlatformShell>;
}
