"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bike, CheckCircle2, Mail, UserRound } from "lucide-react";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
import { useRouter } from "next/navigation";
import PlatformShell from "../../components/PlatformShell";
import { auth } from "../../lib/firebase";
import { createDriverApplication, registerProfile } from "../../lib/firestore";

export default function DriverApplication() {
  const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  async function apply(event) { event.preventDefault(); setLoading(true); setStatus(""); const data = new FormData(event.currentTarget); let credential; try { credential = await createUserWithEmailAndPassword(auth, data.get("email"), data.get("password")); } catch (authError) { if (authError.code !== "auth/email-already-in-use") { setStatus("Impossible de créer le compte Firebase."); setLoading(false); return; } try { credential = await signInWithEmailAndPassword(auth, data.get("email"), data.get("password")); } catch { setStatus("Cet e-mail possède déjà un compte. Connectez-vous ou utilisez son mot de passe pour finaliser le profil."); setLoading(false); return; } } try { await registerProfile(credential.user, { displayName: `${data.get("firstName")} ${data.get("lastName")}`, phone: data.get("phone"), role: "driver" }); await createDriverApplication(credential.user.uid, { firstName: data.get("firstName"), lastName: data.get("lastName"), phone: data.get("phone"), city: data.get("city"), gender: data.get("gender") }); router.push("/espace-livreur"); } catch { setStatus("Le compte Firebase existe, mais Firestore bloque le profil. Publiez les règles puis réessayez avec les mêmes identifiants."); } finally { setLoading(false); } }
  return <PlatformShell><main className="onboarding-page driver-application"><Link className="back-link" href="/"><ArrowLeft size={17} />Retour à Miamgo</Link><div className="onboarding-title"><p className="eyebrow">COMPTE LIVREUR</p><h1>Livrez les repas de votre ville.</h1><p>Votre compte livreur est réservé aux courses, à votre disponibilité et à votre historique de gains.</p></div><form className="onboarding-form" onSubmit={apply}><section><Bike size={28} className="application-icon" /><h2>Votre compte livreur</h2><label><UserRound size={14} />Prénom<input name="firstName" required placeholder="Votre prénom" /></label><label>Nom<input name="lastName" required placeholder="Votre nom" /></label><label><Mail size={14} />Adresse e-mail<input name="email" type="email" required placeholder="livreur@exemple.com" /></label><label>Mot de passe<input name="password" type="password" required minLength="6" placeholder="6 caractères minimum" /></label><label>Numéro WhatsApp<input name="phone" required placeholder="+229 00 00 00 00" /></label><label>Ville<select name="city" defaultValue="Cotonou"><option>Cotonou</option><option>Porto-Novo</option><option>Abidjan</option><option>Lomé</option></select></label><label>Genre<select name="gender" defaultValue=""><option value="" disabled>Choisir</option><option>Femme</option><option>Homme</option><option>Préfère ne pas préciser</option></select></label></section><button className="create-restaurant" type="submit" disabled={loading}>{loading ? "Création..." : "Créer mon compte livreur"}</button>{status && <p className="onboarding-status"><CheckCircle2 size={15} />{status}</p>}<p className="onboarding-login">Déjà inscrit? <Link href="/connexion">Se connecter</Link></p></form></main></PlatformShell>;
}
