"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bike, Upload } from "lucide-react";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { useRouter } from "next/navigation";
import PlatformShell from "../../components/PlatformShell";
import { auth } from "../../lib/firebase";
import { createDriverAffiliation, createDriverApplication, publishDriverDirectory, registerProfile } from "../../lib/firestore";
import { uploadImageFile } from "../../lib/storage";
import { explainAuthError } from "../../lib/firebaseErrors";

export default function DriverApplication() {
  const [restaurantId, setRestaurantId] = useState(null); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false); const [idFile, setIdFile] = useState(null); const router = useRouter();
  useEffect(() => setRestaurantId(new URLSearchParams(window.location.search).get("restaurant")), []);
  async function apply(event) { event.preventDefault(); const data = new FormData(event.currentTarget); if (!idFile) { setStatus("La photo de la pièce d’identité est obligatoire."); return; } setLoading(true); setStatus(""); try { const credential = await createUserWithEmailAndPassword(auth, data.get("email"), data.get("password")); const profile = { displayName: `${data.get("firstName")} ${data.get("lastName")}`, phone: data.get("phone"), country: data.get("country"), city: data.get("city"), role: "driver", verificationStatus: "pending", subscriptionStatus: "locked", availabilityStatus: "unavailable" }; await registerProfile(credential.user, profile); const identityDocumentUrl = await uploadImageFile(idFile, { maxWidth: 1800, quality: .82 }); await createDriverApplication(credential.user.uid, { firstName: data.get("firstName"), lastName: data.get("lastName"), phone: data.get("phone"), city: data.get("city"), country: data.get("country"), gender: data.get("gender"), identityDocumentUrl, restaurantInvitation: restaurantId || null }); await publishDriverDirectory(credential.user.uid, profile); if (restaurantId) await createDriverAffiliation(credential.user.uid, restaurantId, restaurantId); router.push("/espace-livreur"); } catch (error) { setStatus(error.code?.startsWith("auth/") ? explainAuthError(error, "Impossible de créer le compte livreur.") : error.message === "phone-already-used" ? "Ce numéro de téléphone est déjà associé à un compte." : "Impossible de créer le compte livreur. Vérifiez les informations et réessayez."); } finally { setLoading(false); } }
  return <PlatformShell publicPage><main className="onboarding-page driver-application"><Link className="back-link" href="/"><ArrowLeft size={17}/>Retour à Miamgo</Link><div className="onboarding-title"><p className="eyebrow">COMPTE LIVREUR</p><h1>Livrez les repas de votre ville.</h1><p>Votre pièce d’identité sera vérifiée avant activation.</p></div><form className="onboarding-form" onSubmit={apply}><section><h2>Vos informations</h2><label>Prénom<input name="firstName" required/></label><label>Nom<input name="lastName" required/></label><label>Téléphone<input name="phone" required placeholder="+229 00 00 00 00"/></label><label>Ville<input name="city" required/></label><label>Pays<select name="country" defaultValue="BJ"><option value="BJ">Bénin</option><option value="CI">Côte d&apos;Ivoire</option><option value="TG">Togo</option></select></label><label>Genre<select name="gender" defaultValue=""><option value="">Non précisé</option><option value="female">Femme</option><option value="male">Homme</option></select></label></section><section><h2>Compte et justificatif</h2><label>Adresse e-mail<input name="email" type="email" required placeholder="vous@exemple.com"/></label><label>Mot de passe<input name="password" type="password" required minLength="6"/></label><label className="file-upload"><Upload size={16}/>Photo de la pièce d’identité<input type="file" accept="image/*" required onChange={(event) => setIdFile(event.target.files?.[0] || null)}/><small>{idFile ? idFile.name : "Choisir un fichier"}</small></label></section>{status && <p className="auth-error">{status}</p>}<button disabled={loading}>{loading ? "Envoi du dossier..." : "Envoyer ma candidature"}</button></form></main></PlatformShell>;
}
