"use client";
import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { LockKeyhole, Plus } from "lucide-react";
import PlatformShell from "../../../components/PlatformShell";
import { auth } from "../../../lib/firebase";
import { addRestaurantMenuItem, getOwnedRestaurant, getRestaurantMenu } from "../../../lib/firestore";
import { uploadImageFile } from "../../../lib/storage";
const categories = ["Tous les plats", "Plats du jour", "Grillades", "Boissons", "Cocktails", "Promotions"];
export default function RestaurantMenu() {
  const [category, setCategory] = useState(categories[0]); const [items, setItems] = useState([]); const [restaurant, setRestaurant] = useState(null); const [adding, setAdding] = useState(false); const [uploading, setUploading] = useState(false); const [status, setStatus] = useState("");
  useEffect(() => { let active = true; onAuthStateChanged(auth, async (user) => { if (!user) return; const owned = await getOwnedRestaurant(user.uid).catch(() => null); if (!active || !owned) return; setRestaurant(owned); setItems(await getRestaurantMenu(owned.id).catch(() => [])); }); return () => { active = false; }; }, []);
  async function add(event) { event.preventDefault(); if (restaurant?.subscriptionStatus !== "active") { setStatus("Un abonnement actif est nécessaire pour ajouter un plat."); return; } const data = new FormData(event.currentTarget); setUploading(true); setStatus(""); try { const file = data.get("image"); const imageUrl = file?.size ? await uploadImageFile(file) : null; const item = { name: data.get("name"), price: data.get("price"), category: data.get("category"), imageUrl }; const created = await addRestaurantMenuItem(restaurant.id, item); setItems((current) => [{ id: created.id, ...item }, ...current]); setAdding(false); event.currentTarget.reset(); } catch (error) { setStatus(error.message || "Impossible d’enregistrer le plat."); } finally { setUploading(false); } }
  const visible = category === categories[0] ? items : items.filter((item) => item.category === category);
  return <PlatformShell><main className="content-wrap restaurant-menu-page"><div className="restaurant-orders-heading"><div><p className="eyebrow">CATALOGUE RESTAURANT</p><h1>Votre menu</h1><p>Gérez vos plats, cocktails, prix et disponibilités.</p></div>{restaurant?.subscriptionStatus === "active" ? <button type="button" onClick={() => setAdding(true)}><Plus size={18}/>Ajouter un plat</button> : <span className="menu-subscription-lock"><LockKeyhole size={16}/>Abonnement requis</span>}</div><div className="menu-category-pills">{categories.map((item) => <button type="button" className={category === item ? "active" : ""} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div>{visible.length === 0 ? <div className="admin-table-placeholder"><h3>Aucun plat dans cette catégorie</h3><p>{restaurant?.subscriptionStatus === "active" ? "Ajoutez votre premier plat depuis votre appareil." : "Activez votre abonnement pour construire votre menu."}</p></div> : <section className="restaurant-menu-list">{visible.map((item) => <article key={item.id}><div className="menu-item-photo" style={item.imageUrl ? { backgroundImage: `url(${item.imageUrl})` } : {}}>{!item.imageUrl && "🍲"}</div><div><span>{item.category}</span><h2>{item.name}</h2><strong>{item.price}</strong></div></article>)}</section>}{adding && <div className="modal-backdrop"><section className="identity-modal"><h2>Ajouter un plat ou cocktail</h2><form onSubmit={add}><label>Nom<input name="name" required/></label><label>Prix<input name="price" required/></label><label>Catégorie<select name="category" defaultValue={categories[1]}>{categories.slice(1).map((item) => <option key={item}>{item}</option>)}</select></label><label>Photo<input name="image" type="file" accept="image/*"/></label><div><button type="button" onClick={() => setAdding(false)}>Annuler</button><button disabled={uploading}>{uploading ? "Enregistrement..." : "Ajouter"}</button></div></form></section></div>}{status && <p className="settings-notice">{status}</p>}</main></PlatformShell>;
}