"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Bike, CheckCircle2, ClipboardList, Clock3, LogOut, MapPin, Navigation, Power, Settings, Wallet } from "lucide-react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import PlatformShell from "../../components/PlatformShell";
import { auth } from "../../lib/firebase";
import { getUserProfile, updateProfileSettings } from "../../lib/firestore";

export default function DriverDashboard() {
  const [user, setUser] = useState(null); const [profile, setProfile] = useState(null); const [notice, setNotice] = useState(""); const router = useRouter();
  useEffect(() => onAuthStateChanged(auth, async (session) => { setUser(session); if (session) setProfile(await getUserProfile(session.uid).catch(() => null)); }), []);
  const verified = profile?.verificationStatus === "approved"; const subscribed = profile?.subscriptionStatus === "active"; const available = profile?.availabilityStatus === "available";
  async function toggleAvailability() { if (!user || !verified || !subscribed) return; const availabilityStatus = available ? "unavailable" : "available"; await updateProfileSettings(user.uid, { availabilityStatus }).then(() => setProfile((current) => ({ ...current, availabilityStatus }))).catch(() => setNotice("Impossible d'enregistrer votre disponibilité.")); }
  async function logout() { await signOut(auth); router.replace("/"); }
  return <PlatformShell><main className="content-wrap driver-dashboard"><header className="driver-dashboard-header"><div><p className="eyebrow">ACCUEIL LIVREUR</p><h1>{profile?.displayName ? `Bonjour, ${profile.displayName}.` : "Mon tableau de bord"}</h1><p>Vos revenus, vos courses et votre disponibilité.</p></div><button className="driver-logout" onClick={logout}><LogOut size={17}/>Déconnexion</button></header><section className={`driver-availability ${available ? "is-available" : ""}`}><div><Power size={24}/><strong>{available ? "Vous êtes disponible" : "Vous êtes indisponible"}</strong><span>{!verified ? "Validation administrative en attente" : !subscribed ? "Abonnement requis pour recevoir des courses" : available ? "Les restaurants peuvent vous proposer des courses" : "Vous n'apparaissez pas dans le fil des livreurs"}</span></div><button onClick={toggleAvailability} disabled={!verified || !subscribed}>{available ? "Passer indisponible" : "Devenir disponible"}</button></section>{notice && <p className="settings-notice">{notice}</p>}<div className="driver-income-grid"><article><Wallet size={22}/><span>Revenus</span><strong>-- FCFA</strong><small>Les revenus apparaîtront après vos premières courses.</small></article><article><ClipboardList size={22}/><span>Courses terminées</span><strong>--</strong><small>Historique non encore alimenté.</small></article><article><Clock3 size={22}/><span>Temps moyen</span><strong>--</strong><small>Calculé avec les courses réelles.</small></article></div><section className="driver-home-actions"><Link href="/espace-livreur/historique"><CheckCircle2 size={21}/><strong>Historique des courses</strong><small>Dates, restaurants et statuts</small></Link><Link href="/espace-livreur/scanner"><Navigation size={21}/><strong>Scanner une livraison</strong><small>Valider le QR du destinataire</small></Link><Link href="/espace-livreur/affiliations"><Bike size={21}/><strong>Restaurants affiliés</strong><small>Voir vos affiliations</small></Link><Link href="/espace-livreur/profil"><Settings size={21}/><strong>Mon profil</strong><small>Photo et informations personnelles</small></Link></section><section className="driver-next-course"><MapPin size={22}/><div><strong>Aucune course en cours</strong><span>Les demandes apparaîtront ici lorsque vous serez disponible.</span></div></section></main></PlatformShell>;
}
