"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, LogOut, MapPin, Power, Wallet } from "lucide-react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import PlatformShell from "../../components/PlatformShell";
import { auth } from "../../lib/firebase";
import { getUserProfile, publishDriverDirectory, updateProfileSettings } from "../../lib/firestore";

export default function DriverDashboard() { const [user,setUser]=useState(null);const[profile,setProfile]=useState(null);const[notice,setNotice]=useState("");const router=useRouter();useEffect(()=>onAuthStateChanged(auth,async(session)=>{setUser(session);if(session)setProfile(await getUserProfile(session.uid).catch(()=>null));}),[]);const verified=profile?.verificationStatus==="approved";const active=profile?.subscriptionStatus==="active";const available=profile?.availabilityStatus==="available";async function toggle(){if(!user||!verified||!active)return;const availabilityStatus=available?"unavailable":"available";try{const nextProfile={...profile,availabilityStatus};await updateProfileSettings(user.uid,{availabilityStatus});await publishDriverDirectory(user.uid,nextProfile);setProfile(nextProfile);}catch{setNotice("Impossible d'enregistrer votre disponibilité.");}}return <PlatformShell><main className="content-wrap driver-dashboard"><header className="driver-dashboard-header"><div><p className="eyebrow">ACCUEIL LIVREUR</p><h1>{profile?.displayName?`Bonjour, ${profile.displayName}.`:"Mon tableau de bord"}</h1><p>Vérifiez votre disponibilité et vos demandes de course.</p></div><button className="driver-logout" onClick={async()=>{await signOut(auth);router.replace("/");}}><LogOut size={17}/>Déconnexion</button></header><section className={`driver-availability ${available?"is-available":""}`}><div><Power size={24}/><strong>{available?"Vous êtes disponible":"Vous êtes indisponible"}</strong><span>{!verified?"Validation administrative en attente":!active?"Abonnement requis":"Les restaurants peuvent vous proposer des courses"}</span></div><button onClick={toggle} disabled={!verified||!active}>{available?"Passer indisponible":"Devenir disponible"}</button></section>{!verified&&<section className="driver-status-notice"><strong>Ton compte est en attente de validation</strong><span>La pièce d’identité doit être vérifiée avant l’accès aux courses.</span></section>}{verified&&!active&&<section className="driver-status-notice"><strong>Ton compte est validé</strong><span>Active ton abonnement pour commencer à recevoir des courses.</span></section>}{notice&&<p className="settings-notice">{notice}</p>}<section className="driver-requests"><MapPin size={30}/><h2>Aucune demande pour le moment</h2><p>Reste disponible, les demandes apparaîtront ici dès qu&apos;un restaurant te proposera une course.</p></section><section className="driver-day-summary"><div><Wallet size={20}/><span>Gain du jour</span><strong>-- FCFA</strong></div><div><CheckCircle2 size={20}/><span>Courses aujourd&apos;hui</span><strong>--</strong></div></section></main></PlatformShell> }
