"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Bike, CheckCircle2, LogOut, MapPin, Navigation, Power, Settings, Wallet } from "lucide-react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import PlatformShell from "../../components/PlatformShell";
import { auth } from "../../lib/firebase";
import { getUserProfile } from "../../lib/firestore";

export default function DriverDashboard() { const [profile,setProfile]=useState(null); const [available,setAvailable]=useState(false); const router=useRouter(); useEffect(()=>onAuthStateChanged(auth,async(user)=>{if(user)setProfile(await getUserProfile(user.uid).catch(()=>null));}),[]); const verified=profile?.verificationStatus==="approved"; const subscribed=profile?.subscriptionStatus==="active"; return <PlatformShell><main className="content-wrap driver-dashboard"><div className="driver-heading"><div><p className="eyebrow">ESPACE LIVREUR</p><h1>{profile?.displayName?`Bonjour, ${profile.displayName}.`:"Mon espace livreur"}</h1><p>Gérez vos courses, votre statut et vos revenus.</p></div><button onClick={async()=>{await signOut(auth);router.push("/");}}><LogOut size={17}/>Déconnexion</button></div><section className="driver-status-card"><Bike size={25}/><div><strong>{!verified?"Validation administrative en attente":!subscribed?"Compte validé, abonnement requis":available?"Vous êtes disponible":"Vous êtes indisponible"}</strong><span>{!verified?"Votre pièce d'identité doit être vérifiée avant l'abonnement.":!subscribed?"Accédez au paiement depuis votre profil.":"Vous pourrez recevoir des demandes de course."}</span></div>{verified&&subscribed&&<button onClick={()=>setAvailable(!available)}><Power size={16}/>{available?"Disponible":"Indisponible"}</button>}</section><div className="driver-feature-grid"><Link href="/espace-livreur/historique"><CheckCircle2 size={22}/><strong>Historique des courses</strong><small>Courses validées et non validées</small></Link><Link href="/espace-livreur/paiement"><Wallet size={22}/><strong>Abonnement & paiements</strong><small>{verified?"Gérer votre abonnement":"Bloqué jusqu'à validation"}</small></Link><Link href="/espace-livreur/scanner"><Navigation size={22}/><strong>Scanner une livraison</strong><small>Valider le QR du destinataire</small></Link><Link href="/espace-livreur/profil"><Settings size={22}/><strong>Mon profil</strong><small>Informations personnelles</small></Link></div></main></PlatformShell>; }
