"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, MapPin, Navigation, PackageCheck, Play, Store } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import PlatformShell from "../../../components/PlatformShell";
import DeliveryTrackingMap from "../../../components/DeliveryTrackingMap";
import { auth } from "../../../lib/firebase";
import { getActiveDriverOrder } from "../../../lib/firestore";
import { startDriverLocationTracking } from "../../../lib/realtimeLocation";

export default function DriverActiveCourse() {
  const [user, setUser] = useState(null); const [order, setOrder] = useState(null); const [requestedOrderId, setRequestedOrderId] = useState(null); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false); const trackingStop = useRef(null);
  useEffect(() => setRequestedOrderId(new URLSearchParams(window.location.search).get("orderId")), []);
  useEffect(() => onAuthStateChanged(auth, async (session) => { setUser(session); if (session) setOrder(await getActiveDriverOrder(session.uid).catch(() => null)); }), []);
  useEffect(() => () => trackingStop.current?.(), []);
  async function accept() { if (!user || !requestedOrderId) return; setLoading(true); try { const token = await user.getIdToken(); const response = await fetch("/api/delivery/accept", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ orderId: requestedOrderId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setOrder(await getActiveDriverOrder(user.uid)); } catch (error) { setStatus(error.message || "Impossible d’accepter cette course."); } finally { setLoading(false); } }
  async function startTrip() { if (!user || !order) return; setLoading(true); try { const token = await user.getIdToken(); const response = await fetch("/api/delivery/start", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ orderId: order.id }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setOrder({ ...order, deliveryStatus: "en_cours_livraison", status: "out_for_delivery", trackingActive: true }); trackingStop.current?.(); trackingStop.current = startDriverLocationTracking(order.id, user.uid); } catch (error) { setStatus(error.message || "Impossible de démarrer la course."); } finally { setLoading(false); } }
  const items = Array.isArray(order?.items) ? order.items : [];
  return <PlatformShell><main className="content-wrap driver-dashboard"><Link className="back-link" href="/espace-livreur"><ArrowLeft size={17}/>Retour au tableau de bord</Link><p className="eyebrow">COURSE EN COURS</p><h1>{order ? order.serialNumber || "Course assignée" : "Aucune course active"}</h1>{order ? <><section className="active-delivery-summary"><div><Store size={20}/><div><span>Restaurant</span><strong>{order.restaurantName || order.restaurantId || "Restaurant Miamgo"}</strong><small>{order.restaurantAddress || "Adresse du restaurant non renseignée"}</small></div></div><div><MapPin size={20}/><div><span>Destinataire</span><strong>{order.customerName || "Client"}</strong><small>{order.deliveryAddress || order.address || "Adresse de livraison non renseignée"}</small></div></div></section><section className="active-delivery-items"><h2><PackageCheck size={20}/>Contenu de la commande</h2>{items.length ? items.map((item, index) => <div key={`${item.id || item.name}-${index}`}><span>{item.quantity || 1} × {item.name || "Article"}</span><strong>{item.price ? `${item.price} FCFA` : ""}</strong></div>) : <p>Le détail des articles n’est pas renseigné.</p>}</section>{order.deliveryStatus === "en_cours_livraison" ? <><DeliveryTrackingMap orderId={order.id} driverId={user.uid} title="Votre position est partagée"/><p className="tracking-instruction"><Navigation size={16}/>Le suivi reste actif jusqu’à la validation du QR de livraison.</p></> : <button className="driver-start-trip" onClick={startTrip} disabled={loading}><Play size={17}/>{loading ? "Démarrage..." : "Démarrer le trajet"}</button>}<Link className="driver-validate-link" href={`/espace-livreur/scanner?order=${order.id}`}><CheckCircle2 size={16}/>Valider la livraison par QR</Link></> : requestedOrderId ? <section className="driver-empty"><PackageCheck size={32}/><h2>Course proposée</h2><p>Acceptez cette course pour l’ajouter à votre espace.</p><button className="driver-start-trip" onClick={accept} disabled={loading}>{loading ? "Acceptation..." : "Accepter la course"}</button></section> : <section className="driver-empty"><Navigation size={34}/><h2>Aucune course active</h2><p>Une course assignée avec ses adresses et sa carte de suivi apparaîtra ici.</p></section>}{status && <p className="settings-notice">{status}</p>}</main></PlatformShell>;
}
