"use client";

import { useState } from "react";
import Link from "next/link";
import { Bike, CheckCircle2, Clock3, MapPin, Phone, Plus, Star, Trash2, X } from "lucide-react";
import PlatformShell from "../../components/PlatformShell";

const seedDrivers = [["Koffi Mensah", "KM", "Libre", "12", "4.9", "#d96b3a"], ["Arnaud Dossou", "AD", "En livraison", "28", "4.8", "#2d6955"], ["Sonia Agossou", "SA", "Indisponible", "9", "5.0", "#586dbe"]];

export default function DriversPage() {
  const [drivers, setDrivers] = useState(seedDrivers);
  const [showInvite, setShowInvite] = useState(false);
  const [history, setHistory] = useState(false);
  const removeDriver = (name) => setDrivers((current) => current.filter((driver) => driver[0] !== name));
  return <PlatformShell><main className="content-wrap drivers-page"><div className="drivers-heading"><div><p className="eyebrow">CHEZ AÏCHA · LIVRAISON</p><h1>Mes livreurs</h1><p>Suivez votre équipe et affectez les courses en quelques secondes.</p></div><button onClick={() => setShowInvite(true)}><Plus size={18} />Inviter un livreur</button></div><div className="driver-stats"><article><Bike size={21} /><div><strong>{drivers.length}</strong><span>Livreurs enregistrés</span></div></article><article><CheckCircle2 size={21} /><div><strong>{drivers.filter((driver) => driver[2] === "Libre").length}</strong><span>Livreur libre</span></div></article><article><Clock3 size={21} /><div><strong>2</strong><span>Courses aujourd&apos;hui</span></div></article></div><section className="drivers-list"><div className="section-heading"><div><p className="eyebrow">VOTRE ÉQUIPE</p><h2>Livreurs internes</h2></div><button className="light-control" onClick={() => setHistory(!history)}>{history ? "Masquer l'historique" : "Historique complet"}</button></div>{history && <p className="inline-notice">37 courses terminées ce mois. Temps moyen de remise: 31 min.</p>}{drivers.map(([name, initials, status, rides, rating, color]) => <article key={name}><span className="driver-avatar" style={{ background: color }}>{initials}</span><div className="driver-info"><h3>{name}</h3><p><span className={status === "Libre" ? "available" : ""} />{status} <i /> {rides} courses <i /> <Star size={13} fill="currentColor" />{rating}</p></div><div className="driver-location"><MapPin size={16} /><span>{status === "En livraison" ? "Vers Fidjrossè" : status === "Libre" ? "Près du restaurant" : "Hors ligne"}</span></div><a className="contact" href="https://wa.me/22900000000" target="_blank"><Phone size={16} />Contacter</a><button className="delete-driver" aria-label={`Supprimer ${name}`} onClick={() => removeDriver(name)}><Trash2 size={17} /></button></article>)}</section><section className="driver-callout"><div><span><Bike size={25} /></span><div><h2>Besoin d&apos;un renfort?</h2><p>Accédez aux livreurs disponibles du réseau Miamgo et aux agences partenaires de votre zone.</p></div></div><Link href="/espace-livreur">Voir les livreurs partenaires</Link></section>{showInvite && <div className="modal-backdrop"><section className="invite-modal"><button onClick={() => setShowInvite(false)}><X size={19} /></button><h2>Inviter un livreur</h2><p>Un lien d&apos;inscription sécurisé sera envoyé par WhatsApp.</p><input placeholder="Numéro WhatsApp du livreur" /><button className="start-delivery" onClick={() => setShowInvite(false)}>Envoyer l&apos;invitation</button></section></div>}</main></PlatformShell>;
}
