import * as Location from "expo-location";
import * as TaskManager from "expo-task-manager";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { doc, setDoc } from "firebase/firestore";
import { db } from "./firebase";
export const LOCATION_TASK = "MIAMGO_DRIVER_LOCATION";
if (!TaskManager.isTaskDefined(LOCATION_TASK)) TaskManager.defineTask(LOCATION_TASK, async ({ data, error }) => { if (error || !data?.locations?.length) return; const driverId = await AsyncStorage.getItem("miamgo_active_driver"); if (!driverId) return; const location = data.locations[0]; await setDoc(doc(db, "driverLocations", driverId), { latitude: location.coords.latitude, longitude: location.coords.longitude, accuracy: location.coords.accuracy || null, updatedAt: new Date() }, { merge: true }); });
export async function startDriverTracking(driverId) { const foreground = await Location.requestForegroundPermissionsAsync(); if (foreground.status !== "granted") throw new Error("location-permission-denied"); const background = await Location.requestBackgroundPermissionsAsync(); if (background.status !== "granted") throw new Error("background-location-permission-denied"); await AsyncStorage.setItem("miamgo_active_driver", driverId); if (!(await Location.hasStartedLocationUpdatesAsync(LOCATION_TASK))) await Location.startLocationUpdatesAsync(LOCATION_TASK, { accuracy: Location.Accuracy.High, timeInterval: 10000, distanceInterval: 30, showsBackgroundLocationIndicator: true, foregroundService: { notificationTitle: "Miamgo", notificationBody: "Votre livraison est en cours." } }); await setDoc(doc(db, "driverLocations", driverId), { tracking: true, updatedAt: new Date() }, { merge: true }); }
export async function stopDriverTracking(driverId) { await AsyncStorage.removeItem("miamgo_active_driver"); if (await Location.hasStartedLocationUpdatesAsync(LOCATION_TASK)) await Location.stopLocationUpdatesAsync(LOCATION_TASK); await setDoc(doc(db, "driverLocations", driverId), { tracking: false, updatedAt: new Date() }, { merge: true }); }
