"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Clock3, MapPin, Search, SlidersHorizontal, Star } from "lucide-react";
import PlatformShell from "../../components/PlatformShell";

const choices = [["Riz & sauces", "36 restaurants", "#e8603e"], ["Grillades", "18 restaurants", "#334f42"], ["Pâtes", "24 restaurants", "#d99b2c"], ["Petit-déjeuner", "12 restaurants", "#7e5745"]];
const results = [["Chez Aïcha", "Riz gras, sauces et grillades", "4.8", "25-35 min", "Cadjèhoun", "CA", "#f9703e"], ["Mami Grill", "Poisson braisé, alloco", "4.9", "30-40 min", "Fidjrossè", "MG", "#245d4c"], ["Le Comptoir de Koffi", "Pâtes et plats du jour", "4.6", "20-30 min", "Akpakpa", "CK", "#1967d2"]];

export default function ExplorerPage() {
  const [query, setQuery] = useState(""); const [filterOpen, setFilterOpen] = useState(false); const [category, setCategory] = useState("");
  const visible = results.filter(([name, type]) => `${name} ${type}`.toLowerCase().includes(query.toLowerCase()));
  return <PlatformShell active="Explorer"><main className="content-wrap explorer-page"><section className="explorer-hero"><p className="eyebrow">TROUVER VOTRE PROCHAIN REPAS</p><h1>Explorez ce qui mijote près de vous.</h1><label className="large-search"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Un plat, un restaurant, une envie..." /><button onClick={() => setQuery(query.trim())}>Rechercher</button></label></section><section className="section-heading"><div><p className="eyebrow">PAR ENVIE</p><h2>{category || "Qu'allez-vous déguster?"}</h2></div><button className="light-control" onClick={() => setFilterOpen(!filterOpen)}><SlidersHorizontal size={16} />Filtres</button></section>{filterOpen && <div className="filter-panel"><button onClick={() => setCategory("")}>Toutes les cuisines</button><button onClick={() => setCategory("Livraison rapide")}>Livraison rapide</button><button onClick={() => setCategory("Promotions")}>Promotions</button></div>}<div className="choice-grid">{choices.map(([title, detail, color]) => <button className="choice-card" key={title} onClick={() => setCategory(title)}><span style={{ background: color }}>{title.slice(0, 1)}</span><strong>{title}</strong><small>{detail}</small><ArrowRight size={17} /></button>)}</div><section className="section-heading results-heading"><div><p className="eyebrow">OUVERTS MAINTENANT</p><h2>Les adresses appréciées</h2></div><Link href="/restaurant/chez-aicha">Voir la carte <ArrowRight size={15} /></Link></section><div className="restaurant-result-grid">{visible.map(([name, type, rating, time, place, initials, color]) => <article className="restaurant-result" key={name}><div className="restaurant-cover" style={{ background: `linear-gradient(135deg, ${color}, #ffd17c)` }}><span>{initials}</span><b>Ouvert</b></div><div className="restaurant-result-info"><h3>{name}</h3><p>{type}</p><div><span><Star size={13} fill="currentColor" />{rating}</span><span><Clock3 size={13} />{time}</span><span><MapPin size={13} />{place}</span></div><Link href="/restaurant/chez-aicha">Voir le menu</Link></div></article>)}</div>{visible.length === 0 && <div className="empty-state"><Search size={34} /><h2>Aucun restaurant trouvé</h2><p>Essayez une autre recherche.</p></div>}</main></PlatformShell>;
}
