"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ImagePlus, LockKeyhole, Send } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import PlatformShell from "../../../components/PlatformShell";
import { auth } from "../../../lib/firebase";
import { createRestaurantPost, getOwnedRestaurant } from "../../../lib/firestore";
import { uploadMediaFile } from "../../../lib/storage";
export default function PublishPost(){const[mediaFile,setMediaFile]=useState(null);const[preview,setPreview]=useState("");const[restaurant,setRestaurant]=useState(null);const[user,setUser]=useState(null);const[status,setStatus]=useState("");const[loading,setLoading]=useState(false);useEffect(()=>onAuthStateChanged(auth,async(session)=>{setUser(session);if(session)setRestaurant(await getOwnedRestaurant(session.uid).catch(()=>null));}),[]);function choose(event){const file=event.target.files?.[0];setMediaFile(file||null);setPreview(file?URL.createObjectURL(file):"");}async function publish(event){event.preventDefault();if(!restaurant||restaurant.subscriptionStatus!=="active"){setStatus("L’activation de votre abonnement est obligatoire avant de publier.");return;}if(!mediaFile||!user){setStatus("Sélectionnez une image ou une vidéo depuis votre appareil.");return;}setLoading(true);const form=new FormData(event.currentTarget);try{const media=await uploadMediaFile(mediaFile);await createRestaurantPost(user.uid,restaurant.id,{restaurantName:restaurant.name,text:form.get("text"),dish:form.get("dish"),price:form.get("price"),mediaUrl:media.url,mediaType:media.mediaType,mediaDuration:media.duration});setStatus(`${media.mediaType==="video"?"Vidéo":"Image"} envoyée. Publication prête.`);event.currentTarget.reset();setMediaFile(null);setPreview("");}catch(error){setStatus(error.message||"Impossible de téléverser le média.");}finally{setLoading(false);}}const subscribed=restaurant?.subscriptionStatus==="active";return <PlatformShell><main className="content-wrap publish-page"><Link className="back-link" href="/espace-resto"><ArrowLeft size={17}/>Retour au dashboard</Link><p className="eyebrow">FIL MIAMGO</p><h1>Publier</h1>{!subscribed&&<section className="publish-paywall"><LockKeyhole size={21}/><div><strong>Abonnement requis</strong><p>Activez votre plan avant de publier.</p></div><Link href="/espace-resto/abonnement">Voir l&apos;abonnement</Link></section>}<form onSubmit={publish}><label>Texte<textarea name="text" required disabled={!subscribed} placeholder="Votre publication..."/></label><label>Image ou vidéo courte<input type="file" accept="image/*,video/mp4,video/webm,video/quicktime" onChange={choose} required disabled={!subscribed}/><small>Vidéo limitée à 50 Mo et 60 secondes.</small></label>{preview&&<div className="publish-preview">{mediaFile?.type.startsWith("video/")?<video src={preview} controls/>:<img src={preview} alt="Aperçu"/>}<span><ImagePlus size={18}/>Aperçu</span></div>}<label>Plat ou promotion<input name="dish" required disabled={!subscribed}/></label><label>Prix<input name="price" required disabled={!subscribed}/></label><button disabled={!subscribed||loading}><Send size={17}/>{loading?"Téléversement...":"Publier"}</button></form>{status&&<p className="settings-notice">{status}</p>}</main></PlatformShell>}
