import Link from "next/link";
import { ArrowRight, Bike, CheckCircle2, MapPin, Store, UtensilsCrossed } from "lucide-react";

const reasons = [
  ["Des plats autour de vous", "Découvrez les menus, promotions et nouveautés des restaurants de votre quartier.", UtensilsCrossed],
  ["Une commande adaptée", "Retrait sur place, livraison chez vous ou envoi d'un repas à un proche.", MapPin],
  ["Des vendeurs indépendants", "Chaque restaurant garde son activité et reçoit ses paiements directement.", Store],
];

export default function LandingPage() {
  return <main className="landing-page"><header className="landing-header"><Link className="brand brand-with-logo" href="/"><img src="/miamgo-logo.png" alt="Logo Miamgo" /><span>miam</span>go<i>.</i></Link><nav><a href="#restaurants">Pour les restaurants</a><a href="#livreurs">Pour les livreurs</a><Link className="landing-login" href="/accueil">Se connecter</Link></nav></header><section className="landing-hero"><div><p className="landing-kicker">LA NOUVELLE FAÇON DE MANGER LOCAL</p><h1>Le bon repas est déjà près de vous.</h1><p>Miamgo rassemble les plats du jour, les bons restaurants et les livreurs de votre ville, au même endroit.</p><div className="landing-actions"><Link href="/accueil">Visiter la plateforme <ArrowRight size={18} /></Link><Link className="secondary" href="/inscription-resto">Mettre mon restaurant en ligne</Link></div><div className="landing-trust"><span><CheckCircle2 size={16} />Sans commission sur vos ventes</span><span><CheckCircle2 size={16} />Pensé pour la CEDEAO</span></div></div><div className="landing-plate"><div className="plate-badge">PLAT DU JOUR<br /><strong>2 500 FCFA</strong></div><div className="plate-illustration"><UtensilsCrossed size={64} /><b>RIZ GRAS<br />AU POULET</b><span>Chez Aïcha · Cotonou</span></div><div className="plate-note">Livraison ou retrait<br /><strong>en quelques clics</strong></div></div></section><section className="landing-reasons"><div className="section-heading"><div><p className="eyebrow">POURQUOI MIAMGO</p><h2>Simple pour vous. Utile pour tous.</h2></div></div><div className="landing-reason-grid">{reasons.map(([title, text, Icon]) => <article key={title}><span><Icon size={23} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="landing-paths"><article id="restaurants"><div><p className="eyebrow">VOUS ÊTES RESTAURANT?</p><h2>Votre boutique, vos menus, vos clients.</h2><p>Publiez vos plats du jour, recevez les commandes, pilotez les livreurs et développez votre activité avec Miamgo.</p><Link href="/inscription-resto">Créer ma boutique <ArrowRight size={16} /></Link></div><Store size={61} /></article><article id="livreurs"><div><p className="eyebrow">VOUS ÊTES LIVREUR?</p><h2>Livrez les repas près de chez vous.</h2><p>Rejoignez un restaurant ou le réseau partenaire, acceptez les courses et suivez vos revenus.</p><Link href="/inscription-livreur">Devenir livreur <ArrowRight size={16} /></Link></div><Bike size={61} /></article></section><footer className="landing-footer"><span>© 2026 Miamgo</span><Link href="/accueil">Explorer les restaurants</Link><Link href="/inscription-resto">Devenir partenaire</Link></footer></main>;
}
