import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import ScrollReveal from "../components/ScrollReveal";
import AccountCarousel from "../components/AccountCarousel";

const paths = [
  ["Commander un repas", "Explorez les plats, enregistrez vos favoris et suivez chaque commande.", "Créer un compte client", "/inscription-client", "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85"],
  ["Mettre son restaurant en ligne", "Créez un compte professionnel distinct pour votre boutique, vos menus et vos commandes.", "Créer un compte restaurant", "/inscription-resto", "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=85"],
  ["Devenir livreur", "Recevez les courses proposées par les restaurants et gérez vos disponibilités.", "Créer un compte livreur", "/inscription-livreur", "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=1200&q=85"],
];

export default function LandingPage() {
  return <main className="landing-page"><section className="landing-fullscreen"><header className="landing-header"><Link className="brand brand-with-logo" href="/"><img src="/miamgo-logo.png" alt="Logo Miamgo" /></Link><nav><a href="#experiences">Découvrir</a><a href="#restaurant">Restaurants</a><Link className="landing-login" href="/connexion">Se connecter</Link></nav></header><ScrollReveal className="landing-glass"><p className="landing-kicker">LE GOÛT DE VOTRE VILLE</p><h1>Un repas qui vous ressemble, à portée de main.</h1><p>Découvrez les plats du jour, commandez chez vos restaurants préférés et faites-vous livrer simplement avec Miamgo.</p><div className="landing-actions"><Link href="/accueil">Découvrir les plats <ArrowRight size={18} /></Link><Link className="secondary" href="/inscription-client">Créer un compte client</Link></div><div className="landing-trust"><span><CheckCircle2 size={16} />Restaurants près de vous</span><span><CheckCircle2 size={16} />Retrait ou livraison</span></div></ScrollReveal></section><AccountCarousel /><section className="landing-experience-sections" id="experiences">{paths.map(([title, text, action, href, image], index) => <ScrollReveal key={title} delay={index * 70}><article className={`experience-hero experience-${index}`} style={{ backgroundImage: `linear-gradient(90deg, rgba(14,42,32,.79), rgba(14,42,32,.12)), url(${image})` }} id={index === 1 ? "restaurant" : undefined}><div><p className="eyebrow">MIAMGO · {index === 0 ? "CLIENT" : index === 1 ? "RESTAURANT" : "LIVREUR"}</p><h2>{title}</h2><p>{text}</p><Link href={href}>{action} <ArrowRight size={17} /></Link></div></article></ScrollReveal>)}</section><footer className="landing-footer"><div className="footer-brand"><img src="/miamgo-logo.png" alt="Miamgo" /><p>Les repas, les restaurants et les livreurs de votre ville, réunis au même endroit.</p></div><div><strong>Découvrir</strong><Link href="/accueil">Explorer les plats</Link><Link href="/inscription-client">Créer un compte</Link></div><div><strong>Professionnels</strong><Link href="/inscription-resto">Inscrire mon restaurant</Link><Link href="/inscription-livreur">Devenir livreur</Link></div><div><strong>Assistance</strong><Link href="/connexion">Se connecter</Link><a href="mailto:contact@miamgo.app">Nous contacter</a></div><small>© 2026 Miamgo · Tous droits réservés</small></footer></main>;
}
