"use client";

import { useEffect, useState } from "react";
import { Check, ChefHat, Clock3, Search, Truck } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import PlatformShell from "../../../components/PlatformShell";
import { auth } from "../../../lib/firebase";
import { getDriverGroupsForRestaurant, getOwnedRestaurant, getRestaurantOrders } from "../../../lib/firestore";

export default function RestaurantOrders() {
  const [restaurant, setRestaurant] = useState(null); const [orders, setOrders] = useState([]); const [drivers, setDrivers] = useState({ affiliated: [], platform: [] }); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(null);
  async function load(user) { const owned = await getOwnedRestaurant(user.uid).catch(() => null); if (!owned) return; setRestaurant(owned); setOrders(await getRestaurantOrders(owned.id).catch(() => [])); setDrivers(await getDriverGroupsForRestaurant(owned.id).catch(() => ({ affiliated: [], platform: [] }))); }
  useEffect(() => { let timer; const stop = onAuthStateChanged(auth, (user) => { if (user) { load(user); timer = window.setInterval(() => load(user), 5000); } }); return () => { stop(); window.clearInterval(timer); }; }, []);
  async function action(orderId, type, driverId) { const user = auth.currentUser; if (!user) return; setLoading(orderId); try { const token = await user.getIdToken(); const response = await fetch("/api/orders/restaurant-action", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ orderId, action: type, driverId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setMessage(type === "preparing" ? "La commande est maintenant en préparation." : type === "ready" ? "Commande marquée comme prête." : "Demande envoyée au livreur."); await load(user); } catch (error) { setMessage(error.message); } finally { setLoading(null); } }
  const offerExpired = (order) => { const value = order.driverOfferExpiresAt?.toMillis?.() || (order.driverOfferExpiresAt?.seconds ? order.driverOfferExpiresAt.seconds * 1000 : 0); return value > 0 && value < Date.now(); };
  return <PlatformShell><main className="content-wrap restaurant-orders"><div className="restaurant-orders-heading"><div><p className="eyebrow">GESTION DES COMMANDES</p><h1>Commandes</h1><p>Faites avancer chaque commande jusqu&apos;à la remise au client.</p></div><Search size={28}/></div>{message && <p className="settings-notice">{message}</p>}{orders.length ? <div className="restaurant-order-list">{orders.map((order) => <article className="restaurant-order-card" key={order.id}><header><div><strong>{order.serialNumber || order.id}</strong><small>{order.deliveryMode === "pickup" ? "Retrait sur place" : "Livraison"} · {order.paymentStatus === "paid" ? "Paiée" : "Paiement en attente"}</small></div><span className={`order-status-tag order-${order.status}`}>{order.status || "pending"}</span></header><div className="restaurant-order-items">{(order.items || []).map((item, index) => <span key={`${item.id}-${index}`}>{item.quantity || 1} × {item.name || item.dish}</span>)}</div><footer>{order.status === "paid" && <button type="button" onClick={() => action(order.id, "preparing")} disabled={loading === order.id}><ChefHat size={15}/>Commencer la préparation</button>}{["preparing", "preparation"].includes(order.status) && <button type="button" onClick={() => action(order.id, "ready")} disabled={loading === order.id}><Check size={15}/>Commande prête</button>}{(order.status === "ready" || (order.status === "driver_requested" && offerExpired(order))) && order.deliveryMode === "delivery" && <select defaultValue="" onChange={(event) => event.target.value && action(order.id, "assign", event.target.value)} disabled={loading === order.id}><option value="">{offerExpired(order) ? "Choisir un autre livreur" : "Choisir un livreur"}</option>{[...drivers.affiliated, ...drivers.platform].map((driver) => <option value={driver.id} key={driver.id}>{driver.displayName || "Livreur"} · {driver.city || "Disponible"}</option>)}</select>}{order.status === "ready" && order.deliveryMode === "pickup" && <span className="order-ready-note"><Clock3 size={15}/>Prête pour le retrait</span>}{order.status === "driver_requested" && !offerExpired(order) && <span className="order-ready-note"><Truck size={15}/>En attente de confirmation du livreur (5 min)</span>}{order.status === "completed" && <span className="order-completed-note"><Check size={15}/>Commande validée</span>}</footer></article>)}</div> : <section className="empty-state"><Clock3 size={32}/><h2>Aucune commande</h2><p>Les commandes payées apparaîtront ici.</p></section>}</main></PlatformShell>;
}
