"use client";
import { useEffect, useRef, useState } from "react";
import { BrowserMultiFormatReader } from "@zxing/browser";
import { Camera, CheckCircle2, ScanLine, X } from "lucide-react";
import { auth } from "../lib/firebase";

export default function ScannerPanel({ purpose, autoStart = false }) {
  const videoRef = useRef(null); const controlsRef = useRef(null); const [camera, setCamera] = useState(false); const [code, setCode] = useState(""); const [result, setResult] = useState(""); const [error, setError] = useState(""); const [validatedOrder, setValidatedOrder] = useState(null); const validating = useRef(false);
  useEffect(() => { if (autoStart || new URLSearchParams(window.location.search).get("autostart") === "1") { const frame = requestAnimationFrame(() => startCamera()); return () => cancelAnimationFrame(frame); } return undefined; }, [autoStart]);
  useEffect(() => () => controlsRef.current?.stop(), []);
  async function startCamera() { if (!navigator.mediaDevices?.getUserMedia) { setError("La caméra nécessite HTTPS et un navigateur compatible."); return; } try { setError(""); const reader = new BrowserMultiFormatReader(); setCamera(true); await new Promise((resolve) => requestAnimationFrame(resolve)); controlsRef.current?.stop(); controlsRef.current = await reader.decodeFromConstraints({ video: { facingMode: { ideal: "environment" }, width: { ideal: 1280 }, height: { ideal: 720 } } }, videoRef.current, (scanResult) => { if (!scanResult || validating.current) return; const value = scanResult.getText(); console.info("[QR_SCAN] decodedText", JSON.stringify(value)); setCode(value); controlsRef.current?.stop(); setCamera(false); validateCode(value); }); } catch (cameraError) { setCamera(false); setError(cameraError?.name === "NotAllowedError" ? "Autorisez la caméra dans les réglages du navigateur." : "Impossible d’ouvrir la caméra. Vérifiez HTTPS et les autorisations."); } }
  function stopCamera() { controlsRef.current?.stop(); setCamera(false); }
  function parseQr(value) { const raw = String(value || "").trim().replace(/[\r\n\t]/g, ""); const canonical = raw.match(/^miamgo\s*:\s*(pickup|delivery)\s*:\s*([^:\s]+)\s*$/i); if (canonical) { const mode = canonical[1].toLowerCase(); return { mode, reference: canonical[2], value: `miamgo:${mode}:${canonical[2]}` }; } try { const url = new URL(raw); const reference = url.searchParams.get("order") || url.searchParams.get("orderId"); if (reference) { const mode = url.searchParams.get("mode") === "delivery" ? "delivery" : "pickup"; return { mode, reference, value: `miamgo:${mode}:${reference}` }; } } catch {} if (/^(MG-[A-Z0-9-]+|[A-Za-z0-9_-]{8,})$/i.test(raw)) { const mode = purpose.toLowerCase().includes("livraison") ? "delivery" : "pickup"; return { mode, reference: raw, value: `miamgo:${mode}:${raw}` }; } return null; }
  async function validateCode(value = code) { const parsed = parseQr(value); if (!parsed || !auth.currentUser) { setError("QR invalide ou session expirée."); return; } validating.current = true; setError(""); setResult("Validation de la commande en cours..."); try { const token = await auth.currentUser.getIdToken(); const response = await fetch(`/api/orders/${encodeURIComponent(parsed.reference)}/validate-qr`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ qr: parsed.value }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setValidatedOrder(payload.order); setCode(payload.order?.serialNumber || parsed.reference); setResult("Commande validée avec succès."); } catch (validationError) { setResult(""); setError(validationError.message || "Validation refusée."); } finally { validating.current = false; } }
  function reset() { setValidatedOrder(null); setCode(""); setResult(""); setError(""); }
  return <section className="scanner-panel"><p className="eyebrow">SCAN SÉCURISÉ</p><h1>{purpose}</h1>{validatedOrder ? <section className="scan-success-card"><div className="scan-success-heading"><CheckCircle2 size={27}/><div><strong>Commande validée</strong><span>{validatedOrder.serialNumber}</span></div></div><div className="scan-customer"><span>{validatedOrder.customerPhoto ? <img src={validatedOrder.customerPhoto} alt=""/> : (validatedOrder.customerName || "C").slice(0, 2).toUpperCase()}</span><strong>{validatedOrder.customerName}</strong></div><div className="scan-validated-items">{(validatedOrder.items || []).map((item, index) => <div key={`${item.id}-${index}`}>{item.imageUrl ? <img src={item.imageUrl} alt=""/> : <i/>}<span>{item.quantity || 1} × {item.name || item.dish}</span><b>{Number(item.price || 0).toLocaleString("fr-FR")} FCFA</b></div>)}</div><button type="button" className="camera-button" onClick={reset}>Terminer</button></section> : <><p>Scannez le QR du client pour valider la remise.</p><div className="camera-frame"><video className={camera ? "" : "camera-video-hidden"} ref={videoRef} autoPlay muted playsInline />{!camera && <div className="camera-placeholder"><ScanLine size={48}/><span>Positionnez le QR dans le cadre</span></div>}</div>{camera ? <button type="button" className="camera-button" onClick={stopCamera}><X size={18}/>Fermer la caméra</button> : <button type="button" className="camera-button" onClick={startCamera}><Camera size={18}/>Ouvrir la caméra</button>}{error && <p className="scan-error">{error}</p>}<form onSubmit={(event) => { event.preventDefault(); validateCode(); }}><label>Numéro de commande<input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Ex. MG-0842" /></label><button type="submit">Valider la commande</button></form>{result && <p className="scan-result"><CheckCircle2 size={17}/>{result}</p>}</>}</section>;
}
