"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bike, LockKeyhole, Mail, Store, UserRound } from "lucide-react";
import { GoogleAuthProvider, signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { useRouter } from "next/navigation";
import { auth } from "../../lib/firebase";
import { getOwnedRestaurant, getUserProfile } from "../../lib/firestore";
export default function LoginPage(){const[error,setError]=useState("");const[loading,setLoading]=useState(false);const router=useRouter();async function redirect(user){try{const profile=await getUserProfile(user.uid);if(profile?.role==="restaurant_owner")return router.replace("/espace-resto");if(profile?.role==="driver")return router.replace("/espace-livreur");router.replace(await getOwnedRestaurant(user.uid)?"/espace-resto":"/accueil");}catch{router.replace("/accueil?profile=unavailable");}}async function login(event){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);try{const credential=await signInWithEmailAndPassword(auth,form.get("email"),form.get("password"));await redirect(credential.user);}catch(error){setError(error.code?.startsWith("auth/")?"E-mail ou mot de passe incorrect.":"Une erreur technique est survenue.");}finally{setLoading(false);}}async function googleLogin(){setLoading(true);setError("");try{const credential=await signInWithPopup(auth,new GoogleAuthProvider());await redirect(credential.user);}catch(error){if(!["auth/popup-closed-by-user","auth/cancelled-popup-request"].includes(error.code))setError("La connexion Google est momentanément indisponible.");}finally{setLoading(false);}}return <main className="auth-page"><Link className="auth-back" href="/"><ArrowLeft size={17}/>Retour à Miamgo</Link><section className="auth-card"><div className="auth-card-brand"><img src="/miamgo-logo.png" alt="Miamgo"/></div><p className="eyebrow">BON RETOUR PARMI NOUS</p><h1>Connectez-vous à votre espace.</h1><p className="auth-intro">Client, restaurant ou livreur: retrouvez vos commandes et vos outils.</p><form onSubmit={login}><label><Mail size={16}/>Adresse e-mail<input name="email" type="email" required placeholder="vous@exemple.com"/></label><label><LockKeyhole size={16}/>Mot de passe<input name="password" type="password" required minLength="6" placeholder="Votre mot de passe"/></label>{error&&<p className="auth-error">{error}</p>}<button disabled={loading}>{loading?"Connexion...":"Se connecter"}</button></form><button className="google-login" onClick={googleLogin} disabled={loading}><b>G</b>Continuer avec Google</button><div className="auth-choices"><p>Pas encore de compte?</p><Link href="/inscription-client"><UserRound size={15}/>Je suis client</Link><Link href="/inscription-resto"><Store size={15}/>Je suis restaurant</Link><Link href="/inscription-livreur"><Bike size={15}/>Je suis livreur</Link></div></section></main>}
