"use client";
import { useEffect, useRef, useState } from "react";
import Script from "next/script";
import { Check, Crown } from "lucide-react";
import PlatformShell from "../../../components/PlatformShell";
import FedaPayCheckout from "../../../components/FedaPayCheckout";
import { auth } from "../../../lib/firebase";
import { getOwnedRestaurant } from "../../../lib/firestore";
const plans=[["Basique",2500,["Boutique en ligne","Menu et commandes"]],["Pro",5000,["Promotions","Livreurs internes","Statistiques"]],["Premium IA",12000,["Agent IA","Recommandations","Tout le plan Pro"]]];
export default function SubscriptionPage(){const[selected,setSelected]=useState("Pro");const[restaurant,setRestaurant]=useState(null);const[transactionId,setTransactionId]=useState(null);const[ready,setReady]=useState(false);const[status,setStatus]=useState("");const ref=useRef(null);useEffect(()=>{if(auth.currentUser)getOwnedRestaurant(auth.currentUser.uid).then(setRestaurant).catch(()=>{});},[]);async function pay(plan){setSelected(plan);if(!auth.currentUser||!restaurant){setStatus("Connectez-vous avec le compte propriétaire du restaurant.");return;}try{const token=await auth.currentUser.getIdToken();const response=await fetch("/api/fedapay/create-subscription",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({restaurantId:restaurant.id,plan})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setTransactionId(String(payload.transaction?.id||payload.transaction?.data?.id));setTimeout(()=>ref.current?.open().catch(error=>setStatus(error.message)),50);}catch(error){setStatus(error.message);}}function complete({reason,transaction}){if(transaction?.status==="approved")setStatus("Paiement reçu. L'abonnement sera activé par le webhook FedaPay.");else if(reason!==window.FedaPay?.DIALOG_DISMISSED)setStatus("Paiement non confirmé. Vous pouvez réessayer.");}const expiry=restaurant?.subscriptionExpiresAt?.seconds?new Date(restaurant.subscriptionExpiresAt.seconds*1000).toLocaleDateString("fr-FR"):"Non défini";return <><Script src="https://cdn.fedapay.com/checkout.js?v=1.1.7" strategy="afterInteractive" onLoad={()=>setReady(true)}/><PlatformShell><main className="content-wrap subscription-page"><p className="eyebrow">ABONNEMENT</p><h1>Votre plan restaurant</h1><section className="subscription-current"><Crown size={25}/><div><strong>Plan actif: {restaurant?.subscriptionStatus==="active"?restaurant.plan:"Aucun plan actif"}</strong><p>Échéance: {expiry}</p></div></section><div className="plan-cards">{plans.map(([name,price,features])=><article className={selected===name?"selected":""} key={name}><button type="button" className="plan-select" onClick={()=>setSelected(name)}><h2>{name}</h2><strong>{price.toLocaleString("fr-FR")} FCFA<small>/mois</small></strong>{features.map(feature=><span key={feature}><Check size={14}/>{feature}</span>)}</button><button type="button" className="activate-plan" onClick={()=>pay(name)} disabled={!ready}>Payer {name}</button></article>)}</div>{status&&<p className="settings-notice">{status}</p>}<FedaPayCheckout ref={ref} transactionId={transactionId} amount={plans.find(plan=>plan[0]===selected)?.[1]} description={`Abonnement Miamgo ${selected}`} customer={auth.currentUser} ready={ready} onComplete={complete} onError={setStatus}/></main></PlatformShell></>}
