"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ClipboardList, Store, UserRound } from "lucide-react";
import { useParams, useRouter } from "next/navigation";

const money = (value) => `${Number(value || 0).toLocaleString("fr-FR")} FCFA`;
const date = (value) => value ? new Date(value?.seconds ? value.seconds * 1000 : value).toLocaleDateString("fr-FR") : "Non défini";

function SubscriptionEditor({ accountType, accountId, currentPlan, currentStatus, onSaved }) {
  const [plan, setPlan] = useState(currentPlan || "Accès administrateur"); const [days, setDays] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function update(mode) { if (mode === "activate" && (!plan || !Number(days))) { setMessage("Sélectionnez un plan et indiquez une durée."); return; } setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "subscription", id: accountId, mode, accountType, plan, durationDays: Number(days) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Action impossible."); setMessage(mode === "activate" ? `Abonnement activé jusqu’au ${date(payload.expiresAt)}.` : "Abonnement désactivé."); onSaved?.(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <section className="admin-subscription-editor"><p className="eyebrow">ABONNEMENT</p><h2>{currentStatus === "active" ? "Abonnement actif" : "Aucun abonnement actif"}</h2><p className="admin-subscription-current">Plan actuel : {currentPlan || "Aucun"}</p>{accountType === "restaurant" ? <label>Plan<select value={plan} onChange={(event) => setPlan(event.target.value)} disabled={busy}><option>Basique</option><option>Pro</option><option>Premium IA</option><option>Accès administrateur</option></select></label> : <label>Plan livreur<input value={plan} onChange={(event) => setPlan(event.target.value)} disabled={busy}/></label>}<label>Durée en jours<input type="number" min="1" max="3650" value={days} onChange={(event) => setDays(event.target.value)} placeholder="Ex. 30" disabled={busy}/></label><div className="admin-subscription-editor-actions"><button className="admin-action success" onClick={() => update("activate")} disabled={busy}>Activer l’abonnement</button><button className="admin-action danger" onClick={() => update("deactivate")} disabled={busy || currentStatus !== "active"}>Désactiver</button></div>{message && <p className="admin-subscription-message">{message}</p>}</section>;
}

export default function AdminDetailPage() {
  const { type, id } = useParams(); const router = useRouter(); const [item, setItem] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/overview?period=all&year=" + new Date().getFullYear(), { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); const source = type === "restaurant" ? payload.restaurants : type === "driver" ? payload.drivers : type === "order" ? payload.orders : payload.users; const found = source?.find((entry) => String(entry.id || entry.uid) === String(id)); if (!found) throw new Error("Fiche introuvable."); setItem(found); }).catch((cause) => setError(cause.message || "Impossible de charger la fiche.")).finally(() => setLoading(false)); }, [type, id]);
  if (loading) return <main className="admin-detail-page"><p>Chargement de la fiche...</p></main>;
  if (error || !item) return <main className="admin-detail-page"><Link href="/admin"><ArrowLeft size={16}/>Retour à l’administration</Link><div className="admin-table-placeholder"><h2>{error || "Fiche introuvable."}</h2></div></main>;
  const title = type === "restaurant" ? item.name || item.id : type === "driver" ? `${item.firstName || ""} ${item.lastName || ""}` : type === "order" ? item.serialNumber || item.id : item.displayName || item.email || item.uid;
  return <main className="admin-detail-page"><Link className="back-link" href="/admin"><ArrowLeft size={16}/>Retour aux listes</Link><header className="admin-detail-page-header"><div><p className="eyebrow">FICHE {type === "restaurant" ? "RESTAURANT" : type === "driver" ? "LIVREUR" : type === "order" ? "COMMANDE" : "UTILISATEUR"}</p><h1>{title}</h1></div><CheckCircle2 size={23}/></header><section className="admin-detail-card"><dl>{type === "restaurant" && <><dt>Catégorie</dt><dd>{item.category || "Non renseignée"}</dd><dt>Ville</dt><dd>{item.city || "Non renseignée"}</dd><dt>Adresse</dt><dd>{item.address || "Non renseignée"}</dd><dt>Plan</dt><dd>{item.plan || "Non défini"}</dd></>}{type === "driver" && <><dt>Téléphone</dt><dd>{item.phone || "Non renseigné"}</dd><dt>Ville</dt><dd>{item.city || "Non renseignée"}</dd><dt>Validation</dt><dd>{item.verificationStatus || "En attente"}</dd><dt>Disponibilité</dt><dd>{item.availabilityStatus || "Indisponible"}</dd></>}{type === "order" && <><dt>Statut</dt><dd>{item.status || "En attente"}</dd><dt>Paiement</dt><dd>{item.paymentStatus || "En attente"}</dd><dt>Client</dt><dd>{item.clientName || item.clientId || "Non renseigné"}</dd><dt>Restaurant</dt><dd>{item.restaurantName || item.restaurantId || "Non renseigné"}</dd><dt>Montant</dt><dd>{money(item.total || item.amount)}</dd></>}{type === "user" && <><dt>E-mail</dt><dd>{item.email || "Non renseigné"}</dd><dt>Téléphone</dt><dd>{item.phone || "Non renseigné"}</dd><dt>Rôle</dt><dd>{item.role || "client"}</dd><dt>Statut</dt><dd>{item.disabled ? "Suspendu" : "Actif"}</dd></>}</dl></section>{(type === "restaurant" || type === "driver") && <SubscriptionEditor accountType={type} accountId={item.id || item.uid} currentPlan={item.plan || item.subscriptionPlan} currentStatus={item.subscriptionStatus} onSaved={() => router.refresh()}/>}</main>;
}