"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Edit3, Eye, Store, Trash2 } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import PlatformShell from "../../../components/PlatformShell";
import { auth } from "../../../lib/firebase";
import { deleteRestaurantPost, getOwnedRestaurant, getRestaurantPosts, updateRestaurantPost } from "../../../lib/firestore";
export default function RestaurantProfile() {
  const [restaurant, setRestaurant] = useState(null); const [posts, setPosts] = useState([]); const [editing, setEditing] = useState(null); const [message, setMessage] = useState("");
  useEffect(() => onAuthStateChanged(auth, async (user) => { if (!user) return; const owned = await getOwnedRestaurant(user.uid).catch(() => null); if (!owned) return; setRestaurant(owned); setPosts(await getRestaurantPosts(owned.id).catch(() => [])); }), []);
  async function remove(postId) { if (!window.confirm("Supprimer définitivement cette publication ?")) return; try { await deleteRestaurantPost(postId); setPosts((current) => current.filter((post) => post.id !== postId)); setMessage("Publication supprimée."); } catch (error) { setMessage(error.message || "Impossible de supprimer la publication."); } }
  async function save(event) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await updateRestaurantPost(editing.id, { text: data.get("text"), dish: data.get("dish"), price: data.get("price") }); setPosts((current) => current.map((post) => post.id === editing.id ? { ...post, text: data.get("text"), dish: data.get("dish"), price: data.get("price") } : post)); setEditing(null); setMessage("Publication modifiée."); } catch (error) { setMessage(error.message || "Impossible de modifier la publication."); } }
  return <PlatformShell><main className="restaurant-profile-page"><section className="restaurant-public-profile"><div className="restaurant-profile-cover"/><div className="restaurant-profile-body"><div className="restaurant-profile-avatar"><Store size={22}/></div><div className="restaurant-profile-title"><p className="eyebrow">PROFIL RESTAURANT</p><h1>{restaurant?.name || "Votre restaurant"}</h1><p>{restaurant?.city || "Les informations de votre établissement apparaîtront ici après sa création."}</p></div></div></section><section className="restaurant-post-history"><div className="section-heading"><div><p className="eyebrow">VOTRE FIL</p><h2>Publications ({posts.length})</h2></div><Link href="/espace-resto/publier">Nouvelle publication</Link></div>{message && <p className="settings-notice">{message}</p>}{posts.length ? <div className="restaurant-profile-posts">{posts.map((post) => <article key={post.id}><div className="restaurant-profile-post-media">{post.mediaType === "video" ? <video src={post.mediaUrl} controls/> : <img src={post.mediaUrl} alt={post.dish || "Publication"}/>}</div><div className="restaurant-profile-post-content"><p>{post.text || "Publication sans texte"}</p><strong>{post.dish || ""} {post.price ? `· ${post.price} FCFA` : ""}</strong><small>{post.createdAt?.toDate?.()?.toLocaleDateString("fr-FR") || "Publication"}</small><div><button type="button" onClick={() => setEditing(post)}><Edit3 size={14}/>Modifier</button><button type="button" onClick={() => remove(post.id)}><Trash2 size={14}/>Supprimer</button><Link href={`/accueil#post-${post.id}`}><Eye size={14}/>Voir</Link></div></div></article>)}</div> : <div className="admin-table-placeholder"><p>Aucune publication réelle pour le moment.</p><Link href="/espace-resto/publier">Créer votre première publication</Link></div>}</section>{editing && <div className="modal-backdrop"><section className="identity-modal"><h2>Modifier la publication</h2><form onSubmit={save}><label>Texte<textarea name="text" defaultValue={editing.text || ""}/></label><label>Plat<input name="dish" defaultValue={editing.dish || ""}/></label><label>Prix<input name="price" defaultValue={editing.price || ""}/></label><div><button type="button" onClick={() => setEditing(null)}>Annuler</button><button>Enregistrer</button></div></form></section></div>}</main></PlatformShell>;
}